### ISSUE TITLE
Thread error? IDE Fatal Erros

### ISSUE THREAD

**Issue by Kewilleen** [Almighty-Alpaca/JetBrains-Discord-Integration#111]
Hi, my intellij asked report to Almighty...

```java

Details: Current thread: Thread[DefaultDispatcher-worker-2,4,Idea Thread Group] 1318438998
; dispatch thread: false; isDispatchThread(): false
SystemEventQueueThread: Thread[AWT-EventQueue-0,6,Idea Thread Group] 1402742111

java.lang.Throwable: Read access is allowed from event dispatch thread or inside read-action only (see com.intellij.openapi.application.Application.runReadAction())
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:164)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertReadAccessAllowed(ApplicationImpl.java:1009)
	at com.intellij.openapi.roots.impl.RootIndex.<init>(RootIndex.java:57)
	at com.intellij.openapi.roots.impl.DirectoryIndexImpl.getRootIndex(DirectoryIndexImpl.java:129)
	at com.intellij.openapi.roots.impl.DirectoryIndexImpl.getInfoForFile(DirectoryIndexImpl.java:142)
	at com.intellij.openapi.roots.impl.FileIndexBase.getInfoForFileOrDirectory(FileIndexBase.java:80)
	at com.intellij.openapi.roots.impl.ProjectFileIndexImpl.getInfoForFileOrDirectory(ProjectFileIndexImpl.java:24)
	at com.intellij.openapi.roots.impl.ProjectFileIndexImpl.getOrderEntriesForFile(ProjectFileIndexImpl.java:116)
	at com.intellij.dvcs.DvcsUtil.getVcsRootForLibraryFile(DvcsUtil.java:367)
	at com.intellij.dvcs.DvcsUtil.guessVcsRoot(DvcsUtil.java:404)
	at com.intellij.dvcs.DvcsUtil.guessRepositoryForFile(DvcsUtil.java:286)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.extensions.git.GitVcsInfoExtension.getCurrentVcsBranch(GitVcsInfoExtension.kt:12)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.extensions.VcsInfoExtension$Companion$getCurrentVcsBranch$1.invoke(VcsInfoExtension.kt:18)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.extensions.VcsInfoExtension$Companion$getCurrentVcsBranch$1.invoke(VcsInfoExtension.kt:11)
	at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:172)
	at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:132)
	at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:156)
	at kotlin.sequences.SequencesKt___SequencesKt.firstOrNull(_Sequences.kt:129)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.extensions.VcsInfoExtension$Companion.getCurrentVcsBranch(VcsInfoExtension.kt:20)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.data.DataService.getDataInternal(DataService.kt:115)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.data.DataService.getData(DataService.kt:49)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.render.RenderService$render$2.invokeSuspend(RenderService.kt:63)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

**Comment by Almighty-Alpaca** [comment]
This is essentially the same bug as #109. I'm closing this one in favor of tracking the progress at a single place.
