### ISSUE TITLE
ARM, Apple Silicon IDE Support for M1 Macs

### ISSUE THREAD

**Issue by ExecutionSpeed** [Almighty-Alpaca/JetBrains-Discord-Integration#150]
Getting issues on M1 Mac with Apple Silicon JetBrains IDEs. Works with PyCharm Pro but fails with the Apple Silicon variant.

<img width="415" alt="image" src="https://user-images.githubusercontent.com/71984529/109749914-7e161d00-7ba9-11eb-9d12-a3741a4e02cc.png">

```
java.lang.UnsatisfiedLinkError: /Users/johndoe/Library/Caches/JetBrains/PyCharm2020.3/tmp/jna16107159031375330297.tmp: dlopen(/Users/johndoe/Library/Caches/JetBrains/PyCharm2020.3/tmp/jna16107159031375330297.tmp, 1): no suitable image found.  Did find:
	/Users/johndoe/Library/Caches/JetBrains/PyCharm2020.3/tmp/jna16107159031375330297.tmp: no matching architecture in universal wrapper
	/Users/johndoe/Library/Caches/JetBrains/PyCharm2020.3/tmp/jna16107159031375330297.tmp: no matching architecture in universal wrapper
	at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
	at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2442)
	at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2498)
	at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2694)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2627)
	at java.base/java.lang.Runtime.load0(Runtime.java:768)
	at java.base/java.lang.System.load(System.java:1837)
	at com.sun.jna.Native.loadNativeDispatchLibraryFromClasspath(Native.java:947)
	at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:922)
	at com.sun.jna.Native.<clinit>(Native.java:190)
	at com.sun.jna.Pointer.<clinit>(Pointer.java:54)
	at com.sun.jna.Structure.<clinit>(Structure.java:2131)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.RpcService.update(RpcService.kt:121)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.RpcService.update$default(RpcService.kt:77)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.render.RenderService$render$2.invokeSuspend(RenderService.kt:75)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

and 

```
java.lang.NoClassDefFoundError: Could not initialize class com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.connection.NativeRpcConnection
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.RpcService.update(RpcService.kt:121)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.RpcService.update$default(RpcService.kt:77)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.render.RenderService$render$2.invokeSuspend(RenderService.kt:75)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

**Comment by ExecutionSpeed** [comment]
Just realized it's a duplicate of #145.
