### ISSUE TITLE
Errors on trying to display diffs in integration

### ISSUE THREAD

**Issue by AstroFloof** [Almighty-Alpaca/JetBrains-Discord-Integration#186]
Here's a giant stacktrace that I'm sure you love trawling through :P
Anyway I think your thing just doesn't know what to do with a diff instead of a file.
```
Access is allowed from event dispatch thread only

com.intellij.openapi.diagnostic.RuntimeExceptionWithAttachments: EventQueue.isDispatchThread()=false Toolkit.getEventQueue()=com.intellij.ide.IdeEventQueue@44d06eef
Current thread: Thread[DefaultDispatcher-worker-4,5,main] 657106993
SystemEventQueueThread: Thread[AWT-EventQueue-0,6,main] 444379694
	at com.intellij.openapi.application.impl.ApplicationImpl.throwThreadAccessException(ApplicationImpl.java:1030)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertIsDispatchThread(ApplicationImpl.java:1005)
	at com.intellij.openapi.vcs.changes.ChangeViewDiffRequestProcessor.getCurrentChangeName(ChangeViewDiffRequestProcessor.java:172)
	at com.intellij.openapi.vcs.changes.ChangesViewManager$ChangesViewToolWindowPanel$6.getCurrentName(ChangesViewManager.java:488)
	at com.intellij.openapi.vcs.changes.EditorTabPreview$EditorTabDiffPreviewVirtualFile$1.invoke(EditorTabPreview.kt:163)
	at com.intellij.openapi.vcs.changes.EditorTabPreview$EditorTabDiffPreviewVirtualFile$1.invoke(EditorTabPreview.kt:162)
	at com.intellij.openapi.vcs.changes.EditorTabDiffPreviewProvider.getEditorTabName(EditorTabPreview.kt:197)
	at com.intellij.openapi.vcs.changes.VcsEditorTabTitleProvider.getEditorTabName(VcsEditorTabTitleProvider.java:30)
	at com.intellij.openapi.vcs.changes.VcsEditorTabTitleProvider.getEditorTabTitle(VcsEditorTabTitleProvider.java:17)
	at com.intellij.openapi.fileEditor.impl.EditorTabTitleProvider.getEditorTabTitle(EditorTabTitleProvider.java:22)
	at com.intellij.openapi.fileEditor.impl.EditorTabPresentationUtil.getEditorTabTitle(EditorTabPresentationUtil.java:21)
	at com.intellij.openapi.fileEditor.impl.EditorTabPresentationUtil.getUniqueEditorTabTitle(EditorTabPresentationUtil.java:32)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.data.DataService$getData$fileUniqueName$1.invoke(DataService.kt:110)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.data.DataService$getData$fileUniqueName$1.invoke(DataService.kt:49)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.utils.AsyncKt$invokeReadAction$$inlined$suspendCoroutine$lambda$1.compute(actions.kt:80)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:841)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.utils.AsyncKt.invokeReadAction(async.kt:55)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.data.DataService.getDataInternal(DataService.kt:108)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.data.DataService$getData$3.invokeSuspend(DataService.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

**Comment by dominik-korsa** [comment]
Can confirm I also get this error when opening a commit diff

**Comment by SuperSajuuk** [comment]
Can confirm the exact same error occurs for me in PyCharm Professional when opening commit diffs.

**Comment by magneticflux-** [comment]
Duplicate of https://github.com/Almighty-Alpaca/JetBrains-Discord-Integration/issues/179

**Comment by AstroFloof** [comment]
Whoops, I did try to find an issue before posting a new one, sorry!
