### ISSUE TITLE
java.lang.IllegalArgumentException: This timeout value is unsupported: 86400000 

### ISSUE THREAD

**Issue by cikalT** [Almighty-Alpaca/JetBrains-Discord-Integration#213]
Got an issue with lastest Android Studio ver `Android Studio Arctic Fox | 2020.3.1 Patch 4 Build #AI-203.7717.56.2031.7935034, built on November 21, 2021`

Log:
```kotlin
java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: This timeout value is unsupported: 86400000
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:787)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:610)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1085)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.IllegalArgumentException: This timeout value is unsupported: 86400000
	at com.intellij.ide.IdeEventQueue.addIdleListener(IdeEventQueue.java:289)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.time.TimeService.load(TimeService.kt:218)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.time.TimeAppLifecycleListener.appStarting(TimeAppLifecycleListener.kt:24)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.intellij.util.messages.impl.MessageBusImpl.invokeListener(MessageBusImpl.java:656)
	at com.intellij.util.messages.impl.MessageBusImpl.deliverMessage(MessageBusImpl.java:426)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpWaitingBuses(MessageBusImpl.java:401)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:383)
	at com.intellij.util.messages.impl.MessageBusImpl.access$100(MessageBusImpl.java:33)
	at com.intellij.util.messages.impl.MessageBusImpl$MessagePublisher.invoke(MessageBusImpl.java:189)
	at com.sun.proxy.$Proxy57.appStarting(Unknown Source)
	at com.intellij.idea.IdeStarter.main(IdeStarter.kt:130)
	at com.intellij.idea.ApplicationLoader$startApp$8.run(ApplicationLoader.kt:239)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:783)
	... 11 more
```

**Comment by Almighty-Alpaca** [comment]
This happens when you set the timeout to 24h or above. IntelliJ's IdeEventQueue doesn't support values that high. They don't really make sense anyway as Discord won't show anything above 24h. If you just want to essentially disable the timeout there's an extra check mark for that next to it.

I'll leave this open though because I think the field should just limit the values you can set.

**Comment by cikalT** [comment]
> This happens when you set the timeout to 24h or above. IntelliJ's IdeEventQueue doesn't support values that high. They don't really make sense anyway as Discord won't show anything above 24h. If you just want to essentially disable the timeout there's an extra check mark for that next to it.
> 
> I'll leave this open though because I think the field should just limit the values you can set.

how do I change the value timeout? The option is I already delete the plugin via LocalData. Everytime I start the Android Studio, then Install the plugin again I have to restart the plugin so the settings can show. And when I restart, it's keep stuck at loading

**Comment by cikalT** [comment]
Okay, I Found the solution. Right after I install the plugin, I need to close my project first. Then after that I can restart my IDE without stuck at loading
