### ISSUE TITLE
2021.3.3: IncorrectOperationException

### ISSUE THREAD

**Issue by flerouwu** [Almighty-Alpaca/JetBrains-Discord-Integration#220]
Experienced the following error whilst programming in Rust:

```java
com.intellij.util.IncorrectOperationException: Sorry but parent: {com.jetbrains.rd.platform.util.lifetime=Lifetime `Anonymous` [Terminated, executing=0, resources=0]} (class com.intellij.openapi.project.impl.DefaultProject) has already been disposed (see the cause for stacktrace) so the child: com.intellij.openapi.project.impl.DefaultProject$1@35aed261 (class com.intellij.openapi.project.impl.DefaultProject$1) will never be disposed
	at com.intellij.openapi.util.ObjectTree.register(ObjectTree.java:53)
	at com.intellij.openapi.util.Disposer.register(Disposer.java:118)
	at com.intellij.openapi.project.impl.DefaultProject$1.compute(DefaultProject.java:46)
	at com.intellij.openapi.project.impl.DefaultProjectTimed.get(DefaultProjectTimed.java:31)
	at com.intellij.openapi.project.impl.DefaultProject.getDelegate(DefaultProject.java:136)
	at com.intellij.openapi.project.impl.DefaultProject.getMessageBus(DefaultProject.java:243)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.getDefaultProject(ProjectManagerImpl.java:208)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.settings.impl.ProjectSettingsImpl.<init>(ProjectSettingsImpl.kt:33)
	at jdk.internal.reflect.GeneratedConstructorAccessor287.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at com.intellij.serviceContainer.ConstructorInjectionKt.instantiateUsingPicoContainer(constructorInjection.kt:52)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClassWithConstructorInjection(ComponentManagerImpl.kt:876)
	at com.intellij.serviceContainer.ServiceComponentAdapter.createAndInitialize(ServiceComponentAdapter.kt:47)
	at com.intellij.serviceContainer.ServiceComponentAdapter.doCreateInstance(ServiceComponentAdapter.kt:37)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstanceUncached(BaseComponentAdapter.kt:113)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance(BaseComponentAdapter.kt:67)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance$default(BaseComponentAdapter.kt:60)
	at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:595)
	at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:569)
	at com.intellij.openapi.client.ClientAwareComponentManager.getFromSelfOrCurrentSession(ClientAwareComponentManager.kt:37)
	at com.intellij.openapi.client.ClientAwareComponentManager.getService(ClientAwareComponentManager.kt:22)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.settings.ProjectSettingsKt.getSettings(ProjectSettings.kt:42)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.data.DataService.getDataInternal(DataService.kt:87)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.data.DataService$getData$3.invokeSuspend(DataService.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

**Comment by Almighty-Alpaca** [comment]
This is a weird one. Did this happen while closing the IDE?

**Comment by Pixwl** [comment]
No, happened while it was running. Just after I had opened a project.

**Comment by flerouwu** [comment]
Closed as this issue has become stale, and the IDE version is old.
