### ISSUE TITLE
java.lang.RuntimeException: jar file cannot be null

### ISSUE THREAD

**Issue by PythonCoderAS** [Almighty-Alpaca/JetBrains-Discord-Integration#226]
I have my suspicions this occurred because I had homebrew update pycharm while it was still open and so the app file was deleted at some point. Probably my fault but I guess it would be nice to know this scenario can happen.

```java
java.lang.RuntimeException: jar file cannot be null
	at com.intellij.lang.javascript.ecmascript6.TypeScriptUtil.getTypeScriptCompilerFolderFile(TypeScriptUtil.java:904)
	at com.intellij.lang.typescript.compiler.TypeScriptCompilerSettings.getDefaultTypeScriptServiceDirectory(TypeScriptCompilerSettings.java:156)
	at com.intellij.lang.typescript.library.TypeScriptServiceDirectoryWatcher.getDefaultServicePath(TypeScriptServiceDirectoryWatcher.java:65)
	at com.intellij.lang.typescript.library.TypeScriptCustomServiceLibrariesRootsProvider.getNonDefaultServiceDirectoryFile(TypeScriptCustomServiceLibrariesRootsProvider.kt:40)
	at com.intellij.lang.typescript.library.TypeScriptCustomServiceLibrariesRootsProvider.access$getNonDefaultServiceDirectoryFile(TypeScriptCustomServiceLibrariesRootsProvider.kt:14)
	at com.intellij.lang.typescript.library.TypeScriptCustomServiceLibrariesRootsProvider$getAdditionalProjectLibraries$file$1.compute(TypeScriptCustomServiceLibrariesRootsProvider.kt:17)
	at com.intellij.lang.typescript.library.TypeScriptCustomServiceLibrariesRootsProvider$getAdditionalProjectLibraries$file$1.compute(TypeScriptCustomServiceLibrariesRootsProvider.kt:14)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:933)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:68)
	at com.intellij.lang.typescript.library.TypeScriptCustomServiceLibrariesRootsProvider.getAdditionalProjectLibraries(TypeScriptCustomServiceLibrariesRootsProvider.kt:17)
	at com.intellij.openapi.roots.impl.RootIndex.buildRootInfo(RootIndex.java:260)
	at com.intellij.openapi.roots.impl.RootIndex.<init>(RootIndex.java:72)
	at com.intellij.openapi.roots.impl.RootIndex.<init>(RootIndex.java:56)
	at com.intellij.openapi.roots.impl.DirectoryIndexImpl.getRootIndex(DirectoryIndexImpl.java:172)
	at com.intellij.openapi.roots.impl.DirectoryIndexImpl.getRootIndex(DirectoryIndexImpl.java:155)
	at com.intellij.openapi.roots.impl.DirectoryIndexImpl.getInfoForFile(DirectoryIndexImpl.java:182)
	at com.intellij.openapi.roots.impl.FileIndexBase.getInfoForFileOrDirectory(FileIndexBase.java:96)
	at com.intellij.openapi.roots.impl.ProjectFileIndexImpl.getInfoForFileOrDirectory(ProjectFileIndexImpl.java:27)
	at com.intellij.openapi.roots.impl.ProjectFileIndexImpl.getModuleForFile(ProjectFileIndexImpl.java:100)
	at com.intellij.openapi.roots.impl.ProjectFileIndexImpl.getModuleForFile(ProjectFileIndexImpl.java:92)
	at com.intellij.openapi.module.ModuleUtilCore.findModuleForFile(ModuleUtilCore.java:80)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.data.DataService$getData$$inlined$runReadAction$1.compute(actions.kt:60)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:920)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.data.DataService.getDataInternal(DataService.kt:227)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.data.DataService.access$getDataInternal(DataService.kt:49)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.data.DataService$getData$3.invokeSuspend(DataService.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
Caused by: java.lang.RuntimeException: jar file cannot be null
	at com.intellij.lang.javascript.ecmascript6.TypeScriptUtil.getTypeScriptCompilerFolderFile(TypeScriptUtil.java:898)
	... 31 more
```

**Comment by Almighty-Alpaca** [comment]
This looks more like an issue inside the TypeScript plugin while. It occurred while this plugin tried to get information about the current module from the IDE.
