### ISSUE TITLE
Status not updating on 2022.3 EAP

### ISSUE THREAD

**Issue by ConsoleLogLuke** [Almighty-Alpaca/JetBrains-Discord-Integration#242]
After updating to IntelliJ IDEA 2022.3 EAP, my Discord status only updates when I run "Force reconnect". When I first open the IDE, my status isn't set at all and every time I switch files, I need to force reconnect again to get it to update. There are no IDE errors when this happens.

I tested this with IntelliJ IDEA Ultimate 2022.3 and CLion 2022.3, and the same issue occurs on both. I'm using version 1.10.0 of the plugin on Windows 11.

This issue is identical to the one that occurred with 2022.1 EAP, which was reported in #218 and fixed by #221.

**Comment by janek515** [comment]
Same problem in Webstorm.
When i click Force reconnect an IDE error occurs.
```
Unhandled exception in [StandaloneCoroutine{Cancelling}@982d4f9, Dispatchers.Default]

java.lang.NoClassDefFoundError: Could not initialize class com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.connection.DiscordRpcConnection
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.RpcService.createConnection(RpcService.kt:152)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.RpcService.access$createConnection(RpcService.kt:41)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.RpcService$update$1.invokeSuspend(RpcService.kt:120)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelled}@982d4f9, Dispatchers.Default]

```

**Comment by Adamiok** [comment]
Experiencing the same error in PhpStorm.
```
Unhandled exception in [StandaloneCoroutine{Cancelling}@43867756, Dispatchers.Default]

java.lang.NoClassDefFoundError: Could not initialize class com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.connection.DiscordRpcConnection
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.RpcService.createConnection(RpcService.kt:152)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.RpcService.access$createConnection(RpcService.kt:41)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.RpcService$update$1.invokeSuspend(RpcService.kt:120)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelled}@43867756, Dispatchers.Default]
```

**Comment by DEtrees95** [comment]
save problem

**Comment by getkirill** [comment]
can confirm in CLion

**Comment by m4heshd** [comment]
Here's the error on stable WebStorm `2022.3`

```
Unhandled exception in [StandaloneCoroutine{Cancelling}@26823e0b, Dispatchers.Default]

java.lang.UnsatisfiedLinkError: Could not find JNA native support
	at com.sun.jna.Native.loadNativeDispatchLibraryFromClasspath(Native.java:940)
	at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:922)
	at com.sun.jna.Native.<clinit>(Native.java:190)
	at com.sun.jna.Pointer.<clinit>(Pointer.java:54)
	at com.sun.jna.Structure.<clinit>(Structure.java:2131)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.RpcService.createConnection(RpcService.kt:152)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.RpcService.access$createConnection(RpcService.kt:41)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.RpcService$update$1.invokeSuspend(RpcService.kt:120)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelled}@26823e0b, Dispatchers.Default]
```
