### ISSUE TITLE
UnsatisfiedLinkError

### ISSUE THREAD

**Issue by CarinaSchoppe** [Almighty-Alpaca/JetBrains-Discord-Integration#244]
```kt
Stacktrace:
Unhandled exception in [StandaloneCoroutine{Cancelling}@17620226, Dispatchers.Default]

java.lang.UnsatisfiedLinkError: Could not find JNA native support
	at com.sun.jna.Native.loadNativeDispatchLibraryFromClasspath(Native.java:940)
	at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:922)
	at com.sun.jna.Native.<clinit>(Native.java:190)
	at com.sun.jna.Pointer.<clinit>(Pointer.java:54)
	at com.sun.jna.Structure.<clinit>(Structure.java:2131)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.RpcService.createConnection(RpcService.kt:152)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.RpcService.access$createConnection(RpcService.kt:41)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.RpcService$update$1.invokeSuspend(RpcService.kt:120)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelled}@17620226, Dispatchers.Default]
```

**Comment by Sewer56** [comment]
I can reproduce this in latest EAP of Rider, on Win10 21H2 on an AMD64 chip.
No more details for now; working on another hobby project.

**Comment by Sewer56** [comment]
From the Dev on Discord 

> In the mean time you can set the environment variable `com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.connection` to `ipc` (either globally or in the IDE).

This worked for me as a workaround.

**Comment by Almighty-Alpaca** [comment]
You can also switch to the EAP channel of the plugin where the behavior above will become default when JetBrains approves the just published version.

**Comment by CarinaSchoppe** [comment]
well how can I switch to the dev channel?

**Comment by Almighty-Alpaca** [comment]
> **How do I get EAP (Early Access Preview) builds?**
> 
> 1) Go to Settings > Plugins
> 2) Click on the three dots at the top
> 3) Select _Manage Plugin Repositories..._
> 4) Click add in the top left corner
> 5) Paste this link <https://plugins.jetbrains.com/plugins/eap/10233>
> 6) If the update isn't displayed immediately close the settings and click on _Help > Check for updates..._

**Comment by snekxs** [comment]
> From the Dev on Discord
> 
> > In the mean time you can set the environment variable `com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.connection` to `ipc` (either globally or in the IDE).
> 
> This worked for me as a workaround.

How does one do this for webstorm? Quite new to this certain IDE

**Comment by WorriedArrow** [comment]
> How does one do this for webstorm? Quite new to this certain IDE

You can set it globally. Assuming you're on Windows, search "Edit the system environment variables" in the start menu and click "Environment Variables..." at the bottom. Then, under "System variables", click new and set the name to `com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.connection` and the value to `ipc`.

**Comment by zHackeed** [comment]
> > How does one do this for webstorm? Quite new to this certain IDE
> 
> You can set it globally. Assuming you're on Windows, search "Edit the system environment variables" in the start menu and click "Environment Variables..." at the bottom. Then, under "System variables", click new and set the name to `com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.connection` and the value to `ipc`.

That can fix the issue with loading the jnas, but auto updating will be broken (will not update the presence until you click the force reload). 

Someone on the discord said that the dev branch works, if you have the time. Compile that version and try if it is working. Gl

Y'all should wait until Almighty pushes an update adding support on 2022.3 or downgrade to a lower version of your IDE.
