### ISSUE TITLE
UnsatisfiedLinkError: Could not find JNA native support

### ISSUE THREAD

**Issue by ColonelKai** [Almighty-Alpaca/JetBrains-Discord-Integration#251]
```Unhandled exception in [StandaloneCoroutine{Cancelling}@6f006170, Dispatchers.Default]

java.lang.UnsatisfiedLinkError: Could not find JNA native support
	at com.sun.jna.Native.loadNativeDispatchLibraryFromClasspath(Native.java:940)
	at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:922)
	at com.sun.jna.Native.<clinit>(Native.java:190)
	at com.sun.jna.Pointer.<clinit>(Pointer.java:54)
	at com.sun.jna.Structure.<clinit>(Structure.java:2131)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.RpcService.createConnection(RpcService.kt:152)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.RpcService.access$createConnection(RpcService.kt:41)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.RpcService$update$1.invokeSuspend(RpcService.kt:120)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelled}@6f006170, Dispatchers.Default]
```
	
```
IntelliJ IDEA 2022.3 Beta (Community Edition)
Build #IC-223.7571.4, built on November 9, 2022
Runtime version: 17.0.5+1-b653.6 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 20
Registry:
    debugger.new.tool.window.layout=true
    ide.experimental.ui=true

Non-Bundled Plugins:
    com.demonwav.minecraft-dev (2022.3-1.5.21)
    com.almightyalpaca.intellij.plugins.discord (1.10.0)

Kotlin: 223-1.7.20-release-201-IJ7571.4
```

Is beta version of IntelliJ not supported? Would be quite sad.

**Comment by Sewer56** [comment]
This is a duplicate of https://github.com/Almighty-Alpaca/JetBrains-Discord-Integration/issues/244#issuecomment-1295903132

**Comment by ColonelKai** [comment]
Apologies
