### ISSUE TITLE
Error when forced reconnect on IntelliJ 2022.3(beta ui)

### ISSUE THREAD

**Issue by pitzzahh** [Almighty-Alpaca/JetBrains-Discord-Integration#254]
### I updated IntelliJ today and I tried the new UI look (beta) and restarts, then Discord integration doesn't work. So, I tried force reconnect and IntelliJ gave me these errors.

```java
Unhandled exception in [StandaloneCoroutine{Cancelling}@10e19fc1, Dispatchers.Default]

java.lang.UnsatisfiedLinkError: Could not find JNA native support
	at com.sun.jna.Native.loadNativeDispatchLibraryFromClasspath(Native.java:940)
	at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:922)
	at com.sun.jna.Native.<clinit>(Native.java:190)
	at com.sun.jna.Pointer.<clinit>(Pointer.java:54)
	at com.sun.jna.Structure.<clinit>(Structure.java:2131)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.RpcService.createConnection(RpcService.kt:152)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.RpcService.access$createConnection(RpcService.kt:41)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.RpcService$update$1.invokeSuspend(RpcService.kt:120)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelled}@10e19fc1, Dispatchers.Default]


Unhandled exception in [StandaloneCoroutine{Cancelling}@1f5a604d, Dispatchers.Default]

java.lang.NoClassDefFoundError: Could not initialize class com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.connection.DiscordRpcConnection
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.RpcService.createConnection(RpcService.kt:152)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.RpcService.access$createConnection(RpcService.kt:41)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.RpcService$update$1.invokeSuspend(RpcService.kt:120)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelled}@1f5a604d, Dispatchers.Default]

```

**Comment by nottyl** [comment]
This is happening on my CLion 2022.3 as well.

**Comment by shabman** [comment]
got this same error today on IntelliJ IDEA Ultimate 2022.3 with Beta UI enabled

**Comment by PerseverantDT** [comment]
It's caused by issue #244, which is present in 2022.3 IDEs.

**Comment by DavideTW** [comment]
> It's caused by issue #244, which is present in 2022.3 IDEs.

Thanks. Solved.

**Comment by pitzzahh** [comment]
forgot to close this: thanks for fixing it
