### ISSUE TITLE
Could not find JNA native support

### ISSUE THREAD

**Issue by MabedZz** [Almighty-Alpaca/JetBrains-Discord-Integration#261]
Hello 
The plugin does work at all with CLion  and shows this error , even tried reinstalling the plugin but nothing solves the issue 

Unhandled exception in [StandaloneCoroutine{Cancelling}@5c565f3f, Dispatchers.Default]

java.lang.UnsatisfiedLinkError: Could not find JNA native support
	at com.sun.jna.Native.loadNativeDispatchLibraryFromClasspath(Native.java:940)
	at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:922)
	at com.sun.jna.Native.<clinit>(Native.java:190)
	at com.sun.jna.Pointer.<clinit>(Pointer.java:54)
	at com.sun.jna.Structure.<clinit>(Structure.java:2131)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.RpcService.createConnection(RpcService.kt:152)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.RpcService.access$createConnection(RpcService.kt:41)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.RpcService$update$1.invokeSuspend(RpcService.kt:120)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelled}@5c565f3f, Dispatchers.Default]

**Comment by luimen6** [comment]
Same

`Unhandled exception in [StandaloneCoroutine{Cancelling}@49c8ef3f, Dispatchers.Default]

java.lang.UnsatisfiedLinkError: Could not find JNA native support
	at com.sun.jna.Native.loadNativeDispatchLibraryFromClasspath(Native.java:940)
	at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:922)
	at com.sun.jna.Native.<clinit>(Native.java:190)
	at com.sun.jna.Pointer.<clinit>(Pointer.java:54)
	at com.sun.jna.Structure.<clinit>(Structure.java:2131)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.RpcService.createConnection(RpcService.kt:152)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.RpcService.access$createConnection(RpcService.kt:41)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.RpcService$update$1.invokeSuspend(RpcService.kt:120)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelled}@49c8ef3f, Dispatchers.Default]
`

**Comment by TeknoSenpai** [comment]
I am also experiencing the same problem, running on WebStorm 2022.3

**Comment by DarkVessel** [comment]
Same thing, experiencing this issue on WebStorm EAP 2022.3

Build #WS-223.7571.168
Runtime version: 19.0.1+10 amd64
VM: OpenJDK 64-Bit Server VM by N/A
Linux 6.0.11-zen1-1-zen, Arch Linux
GC: G1 Young Generation, G1 Old Generation
Memory: 982M
Cores: 4
Registry:
    debugger.new.tool.window.layout=true
    ide.experimental.ui=true

Non-Bundled Plugins:
    some.awesome (1.14)
    com.thvardhan.gradianto (4.5)
    com.wakatime.intellij.plugin (14.1.1)
    com.jetbrains.darkPurpleTheme (1.3)
    ru.adelf.idea.dotenv (2022.3)
    com.almightyalpaca.intellij.plugins.discord (1.10.0)
    mobi.hsz.idea.gitignore (4.4.4)

Current Desktop: KDE

**Comment by MrAmos123** [comment]
Experiencing the same problem on Rider 2022.3

**Comment by BeChris100** [comment]
Receiving the same error. I believe that the native library was not built for Linux distributions (or it is not built for all platforms), but I'm not entirely sure. Running on Arch Linux with 16 GB of RAM, holding around 300 GB of Storage. CPU works fine on KDE.

**Comment by AwesomeBFM** [comment]
I guess no need to say this but I am also seeing across five different JetBrains products all on 2022.3. It appears to only have started after I updated it to 2022.3. Running Windows 11

**Comment by malafk** [comment]
The issue is since Jetbrains upgraded so the developer has to update the plugin

**Comment by TeknoSenpai** [comment]
> The issue is since Jetbrains upgraded so the developer has to update the plugin

Yes, we know, but, he MUST have upgraded the plugin or at least the MANIFEST, because otherwise the plugin wouldn't start **at all** in any `2022.3` version IDE, throwing an "Incompatible IDE Version" error at startup. 
Thus, the developer **should** update his plugin again.

**Comment by TeknoSenpai** [comment]
> Receiving the same error. I believe that the native library was not built for Linux distributions (or it is not built for all platforms), but I'm not entirely sure. Running on Arch Linux with 16 GB of RAM, holding around 300 GB of Storage. CPU works fine on KDE.

@BeChris100 -> The library works fine with Arch Linux and Manjaro, I've had it for months now (maybe even more than a year) and it never gave me any problems with RTC on Linux.

**Comment by pawelkuwa** [comment]
`Unhandled exception in [StandaloneCoroutine{Cancelling}@6b054174, Dispatchers.Default]

java.lang.UnsatisfiedLinkError: Could not find JNA native support
	at com.sun.jna.Native.loadNativeDispatchLibraryFromClasspath(Native.java:940)
	at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:922)
	at com.sun.jna.Native.<clinit>(Native.java:190)
	at com.sun.jna.Pointer.<clinit>(Pointer.java:54)
	at com.sun.jna.Structure.<clinit>(Structure.java:2131)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.RpcService.createConnection(RpcService.kt:152)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.RpcService.access$createConnection(RpcService.kt:41)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.RpcService$update$1.invokeSuspend(RpcService.kt:120)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelled}@6b054174, Dispatchers.Default]
`

same thing with w10

**Comment by Inui-senpai** [comment]
Same error on PyCharm Community Edition 2022.3.

**Comment by JasonLovesDoggo** [comment]
A fix is to use the EAP build

How do I get EAP (Early Access Preview) builds?
1) Go to Settings > Plugins
2) Click on the three dots at the top
3) Select Manage Plugin Repositories...
4) Click add in the top left corner
5) Paste this link https://plugins.jetbrains.com/plugins/eap/10233
6) If the update isn't displayed immediately close the settings and click on Help > Check for updates..


the only issue is that It doesn't auto-update when you change files so you have to go to tools > discord > force render update.

**Comment by plaam** [comment]
> A fix is to use the EAP build
> 
> How do I get EAP (Early Access Preview) builds?
> 
> 1. Go to Settings > Plugins
> 2. Click on the three dots at the top
> 3. Select Manage Plugin Repositories...
> 4. Click add in the top left corner
> 5. Paste this link https://plugins.jetbrains.com/plugins/eap/10233
> 6. If the update isn't displayed immediately close the settings and click on Help > Check for updates..
> 
> the only issue is that It doesn't auto-update when you change files so you have to go to tools > discord > force render update.
> 
> (works on Pycharm Professional 2022.3 at least.)

Doesn't seem to be working on Rider 2022.3 version.

**Comment by NotJansel** [comment]
> A fix is to use the EAP build
> 
> How do I get EAP (Early Access Preview) builds?
> 
> 1. Go to Settings > Plugins
> 2. Click on the three dots at the top
> 3. Select Manage Plugin Repositories...
> 4. Click add in the top left corner
> 5. Paste this link https://plugins.jetbrains.com/plugins/eap/10233
> 6. If the update isn't displayed immediately close the settings and click on Help > Check for updates..
> the only issue is that It doesn't auto-update when you change files so you have to go to tools > discord > force render update.
> 
> (works on Pycharm Professional 2022.3 at least.)

doesnt work on IntelliJ 2022.3

**Comment by JasonLovesDoggo** [comment]
> > A fix is to use the EAP build
> > 
> > How do I get EAP (Early Access Preview) builds?
> > 
> > 1. Go to Settings > Plugins
> > 2. Click on the three dots at the top
> > 3. Select Manage Plugin Repositories...
> > 4. Click add in the top left corner
> > 5. Paste this link https://plugins.jetbrains.com/plugins/eap/10233
> > 6. If the update isn't displayed immediately close the settings and click on Help > Check for updates..
> > the only issue is that It doesn't auto-update when you change files so you have to go to tools > discord > force render update.
> > 
> > (works on Pycharm Professional 2022.3 at least.)
> 
> doesnt work on IntelliJ 2022.3

intelliJ Ultimate?

**Comment by MrEluzium** [comment]
Seems like it worked for me on IntelliJ 2022.3 Community

![image](https://user-images.githubusercontent.com/57563995/207192595-80d9871c-2d89-4fc8-ad90-b377a02d83aa.png)


> > A fix is to use the EAP build
> > How do I get EAP (Early Access Preview) builds?
> > 
> > 1. Go to Settings > Plugins
> > 2. Click on the three dots at the top
> > 3. Select Manage Plugin Repositories...
> > 4. Click add in the top left corner
> > 5. Paste this link https://plugins.jetbrains.com/plugins/eap/10233
> > 6. If the update isn't displayed immediately close the settings and click on Help > Check for updates..
> >    the only issue is that It doesn't auto-update when you change files so you have to go to tools > discord > force render update.
> > 
> > (works on Pycharm Professional 2022.3 at least.)
> 
> doesnt work on IntelliJ 2022.3

**Comment by NotJansel** [comment]
> > > A fix is to use the EAP build
> > > 
> > > How do I get EAP (Early Access Preview) builds?
> > > 
> > > 1. Go to Settings > Plugins
> > > 2. Click on the three dots at the top
> > > 3. Select Manage Plugin Repositories...
> > > 4. Click add in the top left corner
> > > 5. Paste this link https://plugins.jetbrains.com/plugins/eap/10233
> > > 6. If the update isn't displayed immediately close the settings and click on Help > Check for updates..
> > > the only issue is that It doesn't auto-update when you change files so you have to go to tools > discord > force render update.
> > > 
> > > (works on Pycharm Professional 2022.3 at least.)
> > 
> > doesnt work on IntelliJ 2022.3
> 
> intelliJ Ultimate? 

IJ Community, but out of nowhere it decided to work again

**Comment by BeChris100** [comment]
> > > > A fix is to use the EAP build
> > > > How do I get EAP (Early Access Preview) builds?
> > > > 
> > > > 1. Go to Settings > Plugins
> > > > 2. Click on the three dots at the top
> > > > 3. Select Manage Plugin Repositories...
> > > > 4. Click add in the top left corner
> > > > 5. Paste this link https://plugins.jetbrains.com/plugins/eap/10233
> > > > 6. If the update isn't displayed immediately close the settings and click on Help > Check for updates..
> > > >    the only issue is that It doesn't auto-update when you change files so you have to go to tools > discord > force render update.
> > > > 
> > > > (works on Pycharm Professional 2022.3 at least.)
> > > 
> > > 
> > > doesnt work on IntelliJ 2022.3
> > 
> > 
> > intelliJ Ultimate?
> 
> IJ Community, but out of nowhere it decided to work again

Did you manage to somehow repair the plugin? Because if not, then maybe downgrading the IDE would be the best, until the Discord Plugin Patch has been applied.

**Comment by NotJansel** [comment]
> 

nvm it broke down again

**Comment by plaam** [comment]
Works on Rider 2022.3 as for now.

**Comment by AlexZeDim** [comment]
![image](https://user-images.githubusercontent.com/907696/207533019-5e2e36d1-3191-4cd1-9f78-efeca44d6f9d.png)

Same error for WS with the new interface. I guess the problem is somehow more relevant with UI than with updating JB software.
