### ISSUE TITLE
Discord Integration not working

### ISSUE THREAD

**Issue by kajov** [Almighty-Alpaca/JetBrains-Discord-Integration#264]
```java
Unhandled exception in [StandaloneCoroutine{Cancelling}@4955fdbd, Dispatchers.Default]

java.lang.UnsatisfiedLinkError: Could not find JNA native support
	at com.sun.jna.Native.loadNativeDispatchLibraryFromClasspath(Native.java:940)
	at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:922)
	at com.sun.jna.Native.<clinit>(Native.java:190)
	at com.sun.jna.Pointer.<clinit>(Pointer.java:54)
	at com.sun.jna.Structure.<clinit>(Structure.java:2131)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.RpcService.createConnection(RpcService.kt:152)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.RpcService.access$createConnection(RpcService.kt:41)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.RpcService$update$1.invokeSuspend(RpcService.kt:120)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelled}@4955fdbd, Dispatchers.Default]
```

**Comment by DonTMover** [comment]
Тоже самое

**Comment by stackpan** [comment]
I have the same issue in Intellij IDEA Ultimate 2022.3

**Comment by Dragonox77** [comment]
Hi,
![image](https://user-images.githubusercontent.com/34002813/207376308-138b899d-77de-456d-8d53-839e75d3d7bc.png)
Same here :)

**Comment by antonschnitzer** [comment]
![image](https://user-images.githubusercontent.com/32676027/207416105-a1a890c3-d958-410d-a714-ebe3d4f907f2.png)
Same

**Comment by Shandeika** [comment]
Same
```Unhandled exception in [StandaloneCoroutine{Cancelling}@6251c9d7, Dispatchers.Default]

java.lang.UnsatisfiedLinkError: Could not find JNA native support
	at com.sun.jna.Native.loadNativeDispatchLibraryFromClasspath(Native.java:940)
	at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:922)
	at com.sun.jna.Native.<clinit>(Native.java:190)
	at com.sun.jna.Pointer.<clinit>(Pointer.java:54)
	at com.sun.jna.Structure.<clinit>(Structure.java:2131)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.RpcService.createConnection(RpcService.kt:152)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.RpcService.access$createConnection(RpcService.kt:41)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.RpcService$update$1.invokeSuspend(RpcService.kt:120)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelled}@6251c9d7, Dispatchers.Default]
```
![image](https://user-images.githubusercontent.com/43181505/207448941-a6c4c359-392b-41c2-a5ee-e11cf0dd4b32.png)

**Comment by RezaNajafianRN** [comment]
@Almighty-Alpaca  @kajov @Winfidonarleyan @antonschnitzer @Dragonox77 @Shandeika

**Comment by PluginYML** [comment]
Same

**Comment by GoetheVonSchiller** [comment]
Same Problem in PyCharm 2022.3 and WebStorm 2022.3

**Comment by AndreyKostenkoS** [comment]
Same. PhpStorm 2022.3

**Comment by fabio1999ita** [comment]
same

```
Unhandled exception in [StandaloneCoroutine{Cancelling}@658de26, Dispatchers.Default]

java.lang.UnsatisfiedLinkError: Could not find JNA native support
	at com.sun.jna.Native.loadNativeDispatchLibraryFromClasspath(Native.java:940)
	at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:922)
	at com.sun.jna.Native.<clinit>(Native.java:190)
	at com.sun.jna.Pointer.<clinit>(Pointer.java:54)
	at com.sun.jna.Structure.<clinit>(Structure.java:2131)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.RpcService.createConnection(RpcService.kt:152)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.RpcService.access$createConnection(RpcService.kt:41)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.RpcService$update$1.invokeSuspend(RpcService.kt:120)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelled}@658de26, Dispatchers.Default]
```

![image](https://user-images.githubusercontent.com/27001568/207732033-4dde0aa4-d52d-4f8e-a4a2-b5be9537bb94.png)

**Comment by breftejk** [comment]
same as above ;]

**Comment by ISlip3890** [comment]
Same here 

```
Unhandled exception in [StandaloneCoroutine{Cancelling}@5ef1a491, Dispatchers.Default]

java.lang.UnsatisfiedLinkError: Could not find JNA native support
	at com.sun.jna.Native.loadNativeDispatchLibraryFromClasspath(Native.java:940)
	at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:922)
	at com.sun.jna.Native.<clinit>(Native.java:190)
	at com.sun.jna.Pointer.<clinit>(Pointer.java:54)
	at com.sun.jna.Structure.<clinit>(Structure.java:2131)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.RpcService.createConnection(RpcService.kt:152)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.RpcService.access$createConnection(RpcService.kt:41)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.RpcService$update$1.invokeSuspend(RpcService.kt:120)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelled}@5ef1a491, Dispatchers.Default]

```

![image](https://user-images.githubusercontent.com/74471699/207917797-82657b82-a7a9-4869-ae9c-38e7aaad6c0e.png)

**Comment by it0na72** [comment]
Same problem here. Was gonna give a review but found the repo 
![idea64_ipY6yu7BiU](https://user-images.githubusercontent.com/56265972/208143020-91754416-6c4b-4c86-b2d5-fad6e961eddb.png)

**Comment by rageyh** [comment]
same

**Comment by syorito-hatsuki** [comment]
![image](https://user-images.githubusercontent.com/33298273/208181172-80658376-de3a-44bb-99b9-3ba4d2a6f193.png)
Same here

**Comment by keqno** [comment]
Same here

**Comment by NotInsertIGN** [comment]
Same here

**Comment by NotInsertIGN** [comment]
![image](https://user-images.githubusercontent.com/85914720/208224722-4850270c-d826-4f54-8686-e8a01de18342.png)
Same here

**Comment by NotInsertIGN** [comment]
![image](https://user-images.githubusercontent.com/85914720/208224751-32fc90d4-b6a6-45d4-b7b2-09cc972e9249.png)
Same here

**Comment by MichelePipi** [comment]
Since it doesn't seem like much has happened with this I'm gonna try and fix it myself, I'll let y'all know what happens

**Comment by janek515** [comment]
@kajov Could you close this? As it was already resolved.
