### ISSUE TITLE
Unhandled exception in [StandaloneCoroutine{Cancelling}@184bbaa5, Dispatchers.Default]

### ISSUE THREAD

**Issue by Matbe9** [Almighty-Alpaca/JetBrains-Discord-Integration#269]
Unhandled exception in [StandaloneCoroutine{Cancelling}@184bbaa5, Dispatchers.Default]

java.lang.NoClassDefFoundError: Could not initialize class com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.connection.DiscordRpcConnection
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.RpcService.createConnection(RpcService.kt:152)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.RpcService.access$createConnection(RpcService.kt:41)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.RpcService$update$1.invokeSuspend(RpcService.kt:120)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelled}@184bbaa5, Dispatchers.Default]

**Comment by Matbe9** [comment]
oh i haven't see there is another issue on the same thing 
Sorry
