### ISSUE TITLE
java.net.SocketException: Connection refused; errno=61

### ISSUE THREAD

**Issue by PythonCoderAS** [Almighty-Alpaca/JetBrains-Discord-Integration#284]
I have no idea what the cause was, because unlike #283 Discord was open.

```
Unhandled exception in [StandaloneCoroutine{Cancelling}@7330e1f4, Dispatchers.Default]

java.net.SocketException: Connection refused; errno=61
	at org.newsclub.net.unix.NativeUnixSocket.connect(Native Method)
	at org.newsclub.net.unix.AFSocketImpl.connect0(AFSocketImpl.java:372)
	at org.newsclub.net.unix.AFSocket.connect0(AFSocket.java:265)
	at org.newsclub.net.unix.AFSocket.connect(AFSocket.java:234)
	at org.newsclub.net.unix.AFSocket.connect(AFSocket.java:229)
	at dev.cbyrne.kdiscordipc.core.socket.impl.UnixSocket.connect(UnixSocket.kt:19)
	at dev.cbyrne.kdiscordipc.core.socket.handler.SocketHandler.connect(SocketHandler.kt:59)
	at dev.cbyrne.kdiscordipc.KDiscordIPC.connect(KDiscordIPC.kt:83)
	at dev.cbyrne.kdiscordipc.KDiscordIPC.connect$default(KDiscordIPC.kt:76)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.connection.DiscordIpcConnection$connect$2.invokeSuspend(DiscordIpcConnection.kt:59)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelled}@7330e1f4, Dispatchers.Default]
```

**Comment by pioupia** [comment]
I've the same issue sometimes. But, it’s not supposed to do that. The plugin should not crash like that, it’s amazing. [Line 59 of the file](https://github.com/Almighty-Alpaca/JetBrains-Discord-Integration/blob/master/plugin/src/main/kotlin/com/almightyalpaca/jetbrains/plugins/discord/plugin/rpc/connection/DiscordIpcConnection.kt#L59), can not normally crash. (I think)

**Comment by dnbln** [comment]
> I've the same issue sometimes. But, it’s not supposed to do that. The plugin should not crash like that, it’s amazing. [Line 59 of the file](https://github.com/Almighty-Alpaca/JetBrains-Discord-Integration/blob/master/plugin/src/main/kotlin/com/almightyalpaca/jetbrains/plugins/discord/plugin/rpc/connection/DiscordIpcConnection.kt#L59), can not normally crash. (I think)

The actual line in 1.11.0 is:

https://github.com/Almighty-Alpaca/JetBrains-Discord-Integration/blob/aaeb7b7f40cfcbc7de2f4272ece27e7122eb029c/plugin/src/main/kotlin/com/almightyalpaca/jetbrains/plugins/discord/plugin/rpc/connection/DiscordIpcConnection.kt#L59

But the master branch wasn't updated in a while.

**Comment by pioupia** [comment]
> > I've the same issue sometimes. But, it’s not supposed to do that. The plugin should not crash like that, it’s amazing. [Line 59 of the file](https://github.com/Almighty-Alpaca/JetBrains-Discord-Integration/blob/master/plugin/src/main/kotlin/com/almightyalpaca/jetbrains/plugins/discord/plugin/rpc/connection/DiscordIpcConnection.kt#L59), can not normally crash. (I think)
> 
> The actual line in 1.11.0 is:
> 
> https://github.com/Almighty-Alpaca/JetBrains-Discord-Integration/blob/aaeb7b7f40cfcbc7de2f4272ece27e7122eb029c/plugin/src/main/kotlin/com/almightyalpaca/jetbrains/plugins/discord/plugin/rpc/connection/DiscordIpcConnection.kt#L59
> 
> But the master branch wasn't updated in a while.

Yes, thank you, sorry !
