### ISSUE TITLE
CLion 2022.3.1 - could not detect a running Discord client

### ISSUE THREAD

**Issue by glucu** [Almighty-Alpaca/JetBrains-Discord-Integration#311]
OS: **Pop!_OS 22.04 LTS**
OS Type: **64-bit**
GNOME Version: **42.5**

Issue: I update CLion to the newest released version (listed on title) and now the Discord client no longer works. I tried uninstalling and reinstalling the plugin.

Here is the stacktrace.txt:

`Unhandled exception in [StandaloneCoroutine{Cancelling}@4b1ced89, Dispatchers.Default]

java.net.SocketException: Connection refused; errno=111
	at org.newsclub.net.unix.NativeUnixSocket.connect(Native Method)
	at org.newsclub.net.unix.AFSocketImpl.connect0(AFSocketImpl.java:372)
	at org.newsclub.net.unix.AFSocket.connect0(AFSocket.java:265)
	at org.newsclub.net.unix.AFSocket.connect(AFSocket.java:234)
	at org.newsclub.net.unix.AFSocket.connect(AFSocket.java:229)
	at dev.cbyrne.kdiscordipc.core.socket.impl.UnixSocket.connect(UnixSocket.kt:19)
	at dev.cbyrne.kdiscordipc.core.socket.handler.SocketHandler.connect(SocketHandler.kt:59)
	at dev.cbyrne.kdiscordipc.KDiscordIPC.connect(KDiscordIPC.kt:83)
	at dev.cbyrne.kdiscordipc.KDiscordIPC.connect$default(KDiscordIPC.kt:76)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.connection.DiscordIpcConnection$connect$2.invokeSuspend(DiscordIpcConnection.kt:59)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelled}@4b1ced89, Dispatchers.Default]
`

**Comment by Retrodad0001** [comment]
I have the same issue but with RustRover IDE.. I don't know if it is related. What I know is that this plugin works with Rider on the same 2 machines I have.
