### ISSUE TITLE
Issue with the plugin, IDE error

### ISSUE THREAD

**Issue by DiamondWolf3404** [Almighty-Alpaca/JetBrains-Discord-Integration#356]
Hey ! Sooo, I wanted to try the plugin, it didn't worked, my IDE gave me a popup and that's pretty much all.
-Windows 10
-PyCharm Professional (2023.1.2) | Installed with JetBrains Toolbox 
-Discord Integration (1.11.0)
-Discord stable (up to date)

**### Screenshot:**

![image](https://github.com/Almighty-Alpaca/JetBrains-Discord-Integration/assets/89540246/b02f5860-e06f-46aa-9bcb-055fca177968)

**### Full error code**
Unhandled exception in [StandaloneCoroutine{Cancelling}@6c61c8c0, Dispatchers.Default]

java.io.IOException: Stream Closed
	at java.base/java.io.RandomAccessFile.read0(Native Method)
	at java.base/java.io.RandomAccessFile.read(RandomAccessFile.java:365)
	at java.base/java.io.RandomAccessFile.readInt(RandomAccessFile.java:837)
	at dev.cbyrne.kdiscordipc.core.socket.impl.WindowsSocket.read(WindowsSocket.kt:38)
	at dev.cbyrne.kdiscordipc.core.socket.handler.SocketHandler$events$1.invokeSuspend(SocketHandler.kt:35)
	at dev.cbyrne.kdiscordipc.core.socket.handler.SocketHandler$events$1.invoke(SocketHandler.kt)
	at dev.cbyrne.kdiscordipc.core.socket.handler.SocketHandler$events$1.invoke(SocketHandler.kt)
	at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
	at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:230)
	at kotlinx.coroutines.flow.internal.ChannelFlowOperatorImpl.flowCollect(ChannelFlow.kt:195)
	at kotlinx.coroutines.flow.internal.ChannelFlowOperator.collectTo$suspendImpl(ChannelFlow.kt:157)
	at kotlinx.coroutines.flow.internal.ChannelFlowOperator.collectTo(ChannelFlow.kt)
	at kotlinx.coroutines.flow.internal.ChannelFlow$collectToFun$1.invokeSuspend(ChannelFlow.kt:60)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelled}@6c61c8c0, Dispatchers.Default]

**Comment by SupahFox** [comment]
I got an IDE error too but the plugin still works lol

**Comment by DiamondWolf3404** [comment]
Doesn't for me

**Comment by noBloodOnTheLeaves** [comment]
Hi, try to update plugin. Open File -> settings -> Pugins -> Discrod Integration.

**Comment by voruti** [comment]
> Discord Integration (1.11.0)

It's up to date. (for me too, have the same problem)

**Comment by anilozgok** [comment]
I already had the latest version when I was getting the error. I uninstalled the plugin for now. I might download the plugin again if the issue is solved.

**Comment by noBloodOnTheLeaves** [comment]
> I already had the latest version when I was getting the error. I uninstalled the plugin for now. I might download the plugin again if the issue is solved.

oh, that's why update to new version helped me, because plugin had reinstalled.

**Comment by anilozgok** [comment]
> > I already had the latest version when I was getting the error. I uninstalled the plugin for now. I might download the plugin again if the issue is solved.
> 
> oh, that's why update to new version helped me, because plugin had reinstalled.

Probably, if I reinstall the plugin maybe that problem will be fixed for me too. But still, it is an issue to fix definitely.

**Comment by NobodyForNothing** [comment]
For me the issue occurs when discord is not open, or when it is closed while the plugin runs. Reinstalling the plugin doesn't fix the issue for me.

**Comment by anilozgok** [comment]
Yes, exactly! I didn't realize that before but I tried right now and it occurs when discord isn't open like you said. And yes reinstalling doesn't fix anything I already reinstalled it 2 or 3 times. Well, I'm going to uninstall it again. My IDE is always open but I don't use Discord very often while I'm working. Thx for the heads up btw. Have a nice one!

**Comment by voruti** [comment]
That's interesting. I have Discord open in the background all the time and still get the error.

**Comment by anilozgok** [comment]
Interesting. I have no clue what is going on in the background.

**Comment by SupahFox** [comment]
It seems that in the PY-231.9161.41 build the error isn't showing anymore.
