### ISSUE TITLE
Error upon startup

### ISSUE THREAD

**Issue by kazuryyx** [Almighty-Alpaca/JetBrains-Discord-Integration#361]
Discord is launched, I am in an IntelliJ project.
Caught error when decoding packet (op: 1, length: 374) 

java.util.NoSuchElementException: Array contains no element matching the predicate.
	at dev.cbyrne.kdiscordipc.data.user.PremiumType$Companion$PremiumTypeSerializer.deserialize(PremiumType.kt:43)
	at dev.cbyrne.kdiscordipc.data.user.PremiumType$Companion$PremiumTypeSerializer.deserialize(PremiumType.kt:29)
	at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:59)
	at kotlinx.serialization.json.internal.AbstractJsonTreeDecoder.decodeSerializableValue(TreeJsonDecoder.kt:51)
	at kotlinx.serialization.internal.TaggedDecoder.decodeSerializableValue(Tagged.kt:206)
	at kotlinx.serialization.internal.TaggedDecoder$decodeNullableSerializableElement$1.invoke(Tagged.kt:288)
	at kotlinx.serialization.internal.TaggedDecoder.tagBlock(Tagged.kt:296)
	at kotlinx.serialization.internal.TaggedDecoder.decodeNullableSerializableElement(Tagged.kt:287)
	at dev.cbyrne.kdiscordipc.data.user.User$$serializer.deserialize(User.kt:7)
	at dev.cbyrne.kdiscordipc.data.user.User$$serializer.deserialize(User.kt:7)
	at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:59)
	at kotlinx.serialization.json.internal.AbstractJsonTreeDecoder.decodeSerializableValue(TreeJsonDecoder.kt:51)
	at kotlinx.serialization.internal.TaggedDecoder.decodeSerializableValue(Tagged.kt:206)
	at kotlinx.serialization.internal.TaggedDecoder$decodeSerializableElement$1.invoke(Tagged.kt:279)
	at kotlinx.serialization.internal.TaggedDecoder.tagBlock(Tagged.kt:296)
	at kotlinx.serialization.internal.TaggedDecoder.decodeSerializableElement(Tagged.kt:279)
	at dev.cbyrne.kdiscordipc.core.event.data.ReadyEventData$$serializer.deserialize(ReadyEventData.kt:7)
	at dev.cbyrne.kdiscordipc.core.event.data.ReadyEventData$$serializer.deserialize(ReadyEventData.kt:7)
	at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:59)
	at kotlinx.serialization.json.internal.AbstractJsonTreeDecoder.decodeSerializableValue(TreeJsonDecoder.kt:51)
	at kotlinx.serialization.internal.TaggedDecoder.decodeSerializableValue(Tagged.kt:206)
	at kotlinx.serialization.internal.TaggedDecoder$decodeSerializableElement$1.invoke(Tagged.kt:279)
	at kotlinx.serialization.internal.TaggedDecoder.tagBlock(Tagged.kt:296)
	at kotlinx.serialization.internal.TaggedDecoder.decodeSerializableElement(Tagged.kt:279)
	at dev.cbyrne.kdiscordipc.core.packet.inbound.impl.DispatchEventPacket$Ready$$serializer.deserialize(DispatchEventPacket.kt:17)
	at dev.cbyrne.kdiscordipc.core.packet.inbound.impl.DispatchEventPacket$Ready$$serializer.deserialize(DispatchEventPacket.kt:17)
	at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:59)
	at kotlinx.serialization.json.internal.AbstractJsonTreeDecoder.decodeSerializableValue(TreeJsonDecoder.kt:51)
	at kotlinx.serialization.json.internal.TreeJsonDecoderKt.readJson(TreeJsonDecoder.kt:24)
	at kotlinx.serialization.json.Json.decodeFromJsonElement(Json.kt:119)
	at kotlinx.serialization.json.JsonContentPolymorphicSerializer.deserialize(JsonContentPolymorphicSerializer.kt:93)
	at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:59)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:36)
	at kotlinx.serialization.json.Json.decodeFromString(Json.kt:100)
	at dev.cbyrne.kdiscordipc.core.packet.pipeline.ByteToMessageDecoder.decode(ByteToMessageDecoder.kt:23)
	at dev.cbyrne.kdiscordipc.core.socket.handler.SocketHandler$events$1.invokeSuspend(SocketHandler.kt:36)
	at dev.cbyrne.kdiscordipc.core.socket.handler.SocketHandler$events$1.invoke(SocketHandler.kt)
	at dev.cbyrne.kdiscordipc.core.socket.handler.SocketHandler$events$1.invoke(SocketHandler.kt)
	at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
	at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:230)
	at kotlinx.coroutines.flow.internal.ChannelFlowOperatorImpl.flowCollect(ChannelFlow.kt:195)
	at kotlinx.coroutines.flow.internal.ChannelFlowOperator.collectTo$suspendImpl(ChannelFlow.kt:157)
	at kotlinx.coroutines.flow.internal.ChannelFlowOperator.collectTo(ChannelFlow.kt)
	at kotlinx.coroutines.flow.internal.ChannelFlow$collectToFun$1.invokeSuspend(ChannelFlow.kt:60)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

**Comment by CyberGaming424** [comment]
Had something similar but different stacktrace: 
`Unhandled exception in [StandaloneCoroutine{Cancelling}@6957327b, Dispatchers.Default]

dev.cbyrne.kdiscordipc.core.error.ConnectionError$NoIPCFile: Failed to find an IPC file. Is Discord open? Is this application allowed to access temporary files?
	at dev.cbyrne.kdiscordipc.core.error.ConnectionError$NoIPCFile.<clinit>(ConnectionError.kt)
	at dev.cbyrne.kdiscordipc.core.socket.handler.SocketHandler.findIPCFile(SocketHandler.kt:95)
	at dev.cbyrne.kdiscordipc.core.socket.handler.SocketHandler.findIPCFile(SocketHandler.kt:99)
	at dev.cbyrne.kdiscordipc.core.socket.handler.SocketHandler.findIPCFile(SocketHandler.kt:99)
	at dev.cbyrne.kdiscordipc.core.socket.handler.SocketHandler.findIPCFile(SocketHandler.kt:99)
	at dev.cbyrne.kdiscordipc.core.socket.handler.SocketHandler.findIPCFile(SocketHandler.kt:99)
	at dev.cbyrne.kdiscordipc.core.socket.handler.SocketHandler.findIPCFile(SocketHandler.kt:99)
	at dev.cbyrne.kdiscordipc.core.socket.handler.SocketHandler.findIPCFile(SocketHandler.kt:99)
	at dev.cbyrne.kdiscordipc.core.socket.handler.SocketHandler.findIPCFile(SocketHandler.kt:99)
	at dev.cbyrne.kdiscordipc.core.socket.handler.SocketHandler.findIPCFile(SocketHandler.kt:99)
	at dev.cbyrne.kdiscordipc.core.socket.handler.SocketHandler.findIPCFile(SocketHandler.kt:99)
	at dev.cbyrne.kdiscordipc.core.socket.handler.SocketHandler.findIPCFile(SocketHandler.kt:99)
	at dev.cbyrne.kdiscordipc.core.socket.handler.SocketHandler.connect(SocketHandler.kt:59)
	at dev.cbyrne.kdiscordipc.KDiscordIPC.connect(KDiscordIPC.kt:83)
	at dev.cbyrne.kdiscordipc.KDiscordIPC.connect$default(KDiscordIPC.kt:76)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.connection.DiscordIpcConnection$connect$2.invokeSuspend(DiscordIpcConnection.kt:59)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelled}@6957327b, Dispatchers.Default]
`

**Comment by L3MONAD3** [comment]
Same Thing but different errors i guess

java.lang.Throwable: IPC error: ErrorEventData(code=4000, message=child "activity" fails because [child "assets" fails because [child "large_text" fails because ["large_text" is not allowed to be empty]]])
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:202)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.connection.DiscordIpcConnection.onError(DiscordIpcConnection.kt:133)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.connection.DiscordIpcConnection.access$onError(DiscordIpcConnection.kt:39)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.connection.DiscordIpcConnection$ipcClient$1$1.invokeSuspend$onError(DiscordIpcConnection.kt:47)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.connection.DiscordIpcConnection$ipcClient$1$1.access$invokeSuspend$onError(DiscordIpcConnection.kt)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.connection.DiscordIpcConnection$ipcClient$1$1$2.invoke(DiscordIpcConnection.kt:47)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.connection.DiscordIpcConnection$ipcClient$1$1$2.invoke(DiscordIpcConnection.kt:47)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.connection.DiscordIpcConnection$ipcClient$1$1$invokeSuspend$$inlined$onEvent$4$1.invokeSuspend(KDiscordIPC.kt:103)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

**Comment by MandarinPine18** [comment]
Discord was open. I believe I've got the same issue:

```
Caught error when decoding packet (op: 1, length: 385) 

java.util.NoSuchElementException: Array contains no element matching the predicate.
	at dev.cbyrne.kdiscordipc.data.user.PremiumType$Companion$PremiumTypeSerializer.deserialize(PremiumType.kt:43)
	at dev.cbyrne.kdiscordipc.data.user.PremiumType$Companion$PremiumTypeSerializer.deserialize(PremiumType.kt:29)
	at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:59)
	at kotlinx.serialization.json.internal.AbstractJsonTreeDecoder.decodeSerializableValue(TreeJsonDecoder.kt:51)
	at kotlinx.serialization.internal.TaggedDecoder.decodeSerializableValue(Tagged.kt:206)
	at kotlinx.serialization.internal.TaggedDecoder$decodeNullableSerializableElement$1.invoke(Tagged.kt:288)
	at kotlinx.serialization.internal.TaggedDecoder.tagBlock(Tagged.kt:296)
	at kotlinx.serialization.internal.TaggedDecoder.decodeNullableSerializableElement(Tagged.kt:287)
	at dev.cbyrne.kdiscordipc.data.user.User$$serializer.deserialize(User.kt:7)
	at dev.cbyrne.kdiscordipc.data.user.User$$serializer.deserialize(User.kt:7)
	at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:59)
	at kotlinx.serialization.json.internal.AbstractJsonTreeDecoder.decodeSerializableValue(TreeJsonDecoder.kt:51)
	at kotlinx.serialization.internal.TaggedDecoder.decodeSerializableValue(Tagged.kt:206)
	at kotlinx.serialization.internal.TaggedDecoder$decodeSerializableElement$1.invoke(Tagged.kt:279)
	at kotlinx.serialization.internal.TaggedDecoder.tagBlock(Tagged.kt:296)
	at kotlinx.serialization.internal.TaggedDecoder.decodeSerializableElement(Tagged.kt:279)
	at dev.cbyrne.kdiscordipc.core.event.data.ReadyEventData$$serializer.deserialize(ReadyEventData.kt:7)
	at dev.cbyrne.kdiscordipc.core.event.data.ReadyEventData$$serializer.deserialize(ReadyEventData.kt:7)
	at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:59)
	at kotlinx.serialization.json.internal.AbstractJsonTreeDecoder.decodeSerializableValue(TreeJsonDecoder.kt:51)
	at kotlinx.serialization.internal.TaggedDecoder.decodeSerializableValue(Tagged.kt:206)
	at kotlinx.serialization.internal.TaggedDecoder$decodeSerializableElement$1.invoke(Tagged.kt:279)
	at kotlinx.serialization.internal.TaggedDecoder.tagBlock(Tagged.kt:296)
	at kotlinx.serialization.internal.TaggedDecoder.decodeSerializableElement(Tagged.kt:279)
	at dev.cbyrne.kdiscordipc.core.packet.inbound.impl.DispatchEventPacket$Ready$$serializer.deserialize(DispatchEventPacket.kt:17)
	at dev.cbyrne.kdiscordipc.core.packet.inbound.impl.DispatchEventPacket$Ready$$serializer.deserialize(DispatchEventPacket.kt:17)
	at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:59)
	at kotlinx.serialization.json.internal.AbstractJsonTreeDecoder.decodeSerializableValue(TreeJsonDecoder.kt:51)
	at kotlinx.serialization.json.internal.TreeJsonDecoderKt.readJson(TreeJsonDecoder.kt:24)
	at kotlinx.serialization.json.Json.decodeFromJsonElement(Json.kt:119)
	at kotlinx.serialization.json.JsonContentPolymorphicSerializer.deserialize(JsonContentPolymorphicSerializer.kt:93)
	at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:59)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:36)
	at kotlinx.serialization.json.Json.decodeFromString(Json.kt:100)
	at dev.cbyrne.kdiscordipc.core.packet.pipeline.ByteToMessageDecoder.decode(ByteToMessageDecoder.kt:23)
	at dev.cbyrne.kdiscordipc.core.socket.handler.SocketHandler$events$1.invokeSuspend(SocketHandler.kt:36)
	at dev.cbyrne.kdiscordipc.core.socket.handler.SocketHandler$events$1.invoke(SocketHandler.kt)
	at dev.cbyrne.kdiscordipc.core.socket.handler.SocketHandler$events$1.invoke(SocketHandler.kt)
	at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
	at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:230)
	at kotlinx.coroutines.flow.internal.ChannelFlowOperatorImpl.flowCollect(ChannelFlow.kt:195)
	at kotlinx.coroutines.flow.internal.ChannelFlowOperator.collectTo$suspendImpl(ChannelFlow.kt:157)
	at kotlinx.coroutines.flow.internal.ChannelFlowOperator.collectTo(ChannelFlow.kt)
	at kotlinx.coroutines.flow.internal.ChannelFlow$collectToFun$1.invokeSuspend(ChannelFlow.kt:60)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```
IntelliJ 2023.1.2

**Comment by obfuscatedgenerated** [comment]
Contributing my stacktrace and version data to the pile:

Plugin version: 1.11.0
IDE: CLion 2023.2

```
  Caught error when decoding packet (op: 1, length: 386) 
  
  java.util.NoSuchElementException: Array contains no element matching the predicate.
at dev.cbyrne.kdiscordipc.data.user.PremiumType$Companion$PremiumTypeSerializer.deserialize(PremiumType.kt:43)
at dev.cbyrne.kdiscordipc.data.user.PremiumType$Companion$PremiumTypeSerializer.deserialize(PremiumType.kt:29)
at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:59)
at kotlinx.serialization.json.internal.AbstractJsonTreeDecoder.decodeSerializableValue(TreeJsonDecoder.kt:51)
at kotlinx.serialization.internal.TaggedDecoder.decodeSerializableValue(Tagged.kt:206)
at kotlinx.serialization.internal.TaggedDecoder$decodeNullableSerializableElement$1.invoke(Tagged.kt:288)
at kotlinx.serialization.internal.TaggedDecoder.tagBlock(Tagged.kt:296)
at kotlinx.serialization.internal.TaggedDecoder.decodeNullableSerializableElement(Tagged.kt:287)
at dev.cbyrne.kdiscordipc.data.user.User$$serializer.deserialize(User.kt:7)
at dev.cbyrne.kdiscordipc.data.user.User$$serializer.deserialize(User.kt:7)
at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:59)
at kotlinx.serialization.json.internal.AbstractJsonTreeDecoder.decodeSerializableValue(TreeJsonDecoder.kt:51)
at kotlinx.serialization.internal.TaggedDecoder.decodeSerializableValue(Tagged.kt:206)
at kotlinx.serialization.internal.TaggedDecoder$decodeSerializableElement$1.invoke(Tagged.kt:279)
at kotlinx.serialization.internal.TaggedDecoder.tagBlock(Tagged.kt:296)
at kotlinx.serialization.internal.TaggedDecoder.decodeSerializableElement(Tagged.kt:279)
at dev.cbyrne.kdiscordipc.core.event.data.ReadyEventData$$serializer.deserialize(ReadyEventData.kt:7)
at dev.cbyrne.kdiscordipc.core.event.data.ReadyEventData$$serializer.deserialize(ReadyEventData.kt:7)
at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:59)
at kotlinx.serialization.json.internal.AbstractJsonTreeDecoder.decodeSerializableValue(TreeJsonDecoder.kt:51)
at kotlinx.serialization.internal.TaggedDecoder.decodeSerializableValue(Tagged.kt:206)
at kotlinx.serialization.internal.TaggedDecoder$decodeSerializableElement$1.invoke(Tagged.kt:279)
at kotlinx.serialization.internal.TaggedDecoder.tagBlock(Tagged.kt:296)
at kotlinx.serialization.internal.TaggedDecoder.decodeSerializableElement(Tagged.kt:279)
at dev.cbyrne.kdiscordipc.core.packet.inbound.impl.DispatchEventPacket$Ready$$serializer.deserialize(DispatchEventPacket.kt:17)
at dev.cbyrne.kdiscordipc.core.packet.inbound.impl.DispatchEventPacket$Ready$$serializer.deserialize(DispatchEventPacket.kt:17)
at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:59)
at kotlinx.serialization.json.internal.AbstractJsonTreeDecoder.decodeSerializableValue(TreeJsonDecoder.kt:51)
at kotlinx.serialization.json.internal.TreeJsonDecoderKt.readJson(TreeJsonDecoder.kt:24)
at kotlinx.serialization.json.Json.decodeFromJsonElement(Json.kt:119)
at kotlinx.serialization.json.JsonContentPolymorphicSerializer.deserialize(JsonContentPolymorphicSerializer.kt:93)
at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:59)
at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:36)
at kotlinx.serialization.json.Json.decodeFromString(Json.kt:100)
at dev.cbyrne.kdiscordipc.core.packet.pipeline.ByteToMessageDecoder.decode(ByteToMessageDecoder.kt:23)
at dev.cbyrne.kdiscordipc.core.socket.handler.SocketHandler$events$1.invokeSuspend(SocketHandler.kt:36)
at dev.cbyrne.kdiscordipc.core.socket.handler.SocketHandler$events$1.invoke(SocketHandler.kt)
at dev.cbyrne.kdiscordipc.core.socket.handler.SocketHandler$events$1.invoke(SocketHandler.kt)
at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:230)
at kotlinx.coroutines.flow.internal.ChannelFlowOperatorImpl.flowCollect(ChannelFlow.kt:195)
at kotlinx.coroutines.flow.internal.ChannelFlowOperator.collectTo$suspendImpl(ChannelFlow.kt:157)
at kotlinx.coroutines.flow.internal.ChannelFlowOperator.collectTo(ChannelFlow.kt)
at kotlinx.coroutines.flow.internal.ChannelFlow$collectToFun$1.invokeSuspend(ChannelFlow.kt:60)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:100)
at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
```

**Comment by dayo05** [comment]
#314
