### ISSUE TITLE
Error on startup when Discord isn't launched

### ISSUE THREAD

**Issue by 10YAR** [Almighty-Alpaca/JetBrains-Discord-Integration#363]
Here's an error that display everytime at startup (on phpStorm) when Discord isn't launched :
I'm on macOS Sonoma (M2) and i'm using the NewUI of phpStorm

```
Unhandled exception in [StandaloneCoroutine{Cancelling}@75ec539c, Dispatchers.Default]

java.net.SocketException: Connection refused; errno=61
	at org.newsclub.net.unix.NativeUnixSocket.connect(Native Method)
	at org.newsclub.net.unix.AFSocketImpl.connect0(AFSocketImpl.java:372)
	at org.newsclub.net.unix.AFSocket.connect0(AFSocket.java:265)
	at org.newsclub.net.unix.AFSocket.connect(AFSocket.java:234)
	at org.newsclub.net.unix.AFSocket.connect(AFSocket.java:229)
	at dev.cbyrne.kdiscordipc.core.socket.impl.UnixSocket.connect(UnixSocket.kt:19)
	at dev.cbyrne.kdiscordipc.core.socket.handler.SocketHandler.connect(SocketHandler.kt:59)
	at dev.cbyrne.kdiscordipc.KDiscordIPC.connect(KDiscordIPC.kt:83)
	at dev.cbyrne.kdiscordipc.KDiscordIPC.connect$default(KDiscordIPC.kt:76)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.connection.DiscordIpcConnection$connect$2.invokeSuspend(DiscordIpcConnection.kt:59)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelled}@75ec539c, Dispatchers.Default]
```

Maybe you should like do nothing (not even throwing errors) when Discord isn't detected

Thanks !

**Comment by luimen6** [comment]
Same here on Ubuntu 22.04.

```
Unhandled exception in [StandaloneCoroutine{Cancelling}@23c3596, Dispatchers.Default]

java.net.SocketException: ; errno=111
	at org.newsclub.net.unix.NativeUnixSocket.connect(Native Method)
	at org.newsclub.net.unix.AFSocketImpl.connect0(AFSocketImpl.java:372)
	at org.newsclub.net.unix.AFSocket.connect0(AFSocket.java:265)
	at org.newsclub.net.unix.AFSocket.connect(AFSocket.java:234)
	at org.newsclub.net.unix.AFSocket.connect(AFSocket.java:229)
	at dev.cbyrne.kdiscordipc.core.socket.impl.UnixSocket.connect(UnixSocket.kt:19)
	at dev.cbyrne.kdiscordipc.core.socket.handler.SocketHandler.connect(SocketHandler.kt:59)
	at dev.cbyrne.kdiscordipc.KDiscordIPC.connect(KDiscordIPC.kt:83)
	at dev.cbyrne.kdiscordipc.KDiscordIPC.connect$default(KDiscordIPC.kt:76)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.connection.DiscordIpcConnection$connect$2.invokeSuspend(DiscordIpcConnection.kt:59)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelled}@23c3596, Dispatchers.Default]
```

**Comment by aliencaocao** [comment]
same issue on windows 10 and 11, I have to disable the plugin because of this, as I may not have discord running when i launch ide but only after.
It also doesn't reconnect if I launch discord after i launch ide, even if i use force reconnect
