### ISSUE TITLE
stacktrace.txt "crash" stops the RPC display

### ISSUE THREAD

**Issue by LeGarsFou** [Almighty-Alpaca/JetBrains-Discord-Integration#367]
So I was using WebStorm and I noticed that my RPC wasn't there on Discord, so I looked on WS and saw an error. I just updated the wakatime plugin, but I don't think this is the cause. I restarted WS and the error disappeared and my RPC was back.

The error :
```
  Unhandled exception in [StandaloneCoroutine{Cancelling}@476797d5, Dispatchers.IO]
  
  java.io.IOException: Le canal de communication est sur le point d’être fermé
at java.base/java.io.RandomAccessFile.writeBytes(Native Method)
at java.base/java.io.RandomAccessFile.write(RandomAccessFile.java:545)
at dev.cbyrne.kdiscordipc.core.socket.impl.WindowsSocket.write(WindowsSocket.kt:48)
at dev.cbyrne.kdiscordipc.core.socket.handler.SocketHandler$1.invokeSuspend(SocketHandler.kt:42)
at dev.cbyrne.kdiscordipc.core.socket.handler.SocketHandler$1.invoke(SocketHandler.kt)
at dev.cbyrne.kdiscordipc.core.socket.handler.SocketHandler$1.invoke(SocketHandler.kt)
at kotlinx.coroutines.flow.FlowKt__TransformKt$onEach$$inlined$unsafeTransform$1$2.emit(Emitters.kt:223)
at kotlinx.coroutines.flow.SharedFlowImpl.collect$suspendImpl(SharedFlow.kt:382)
at kotlinx.coroutines.flow.SharedFlowImpl$collect$1.invokeSuspend(SharedFlow.kt)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:100)
at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelled}@476797d5, Dispatchers.IO]
```

**Comment by AnubisXHyperX** [comment]
Same here
