### ISSUE TITLE
Issues on Linux with InteliJ 2022.3

### ISSUE THREAD

**Issue by AzhamProdLive** [Almighty-Alpaca/JetBrains-Discord-Integration#369]
Hi, as stated in the title, i'm facing issues with this plugin when trying to use it on Linux. I'm getting the following errors :
```
java.lang.Throwable: Must be precomputed
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:370)
	at com.intellij.ui.scale.JBUIScale.computeSystemScaleFactor(JBUIScale.kt:188)
	at com.intellij.ui.scale.JBUIScale$systemScaleFactor$1.invoke(JBUIScale.kt:67)
	at com.intellij.ui.scale.JBUIScale$systemScaleFactor$1.invoke(JBUIScale.kt:66)
	at com.intellij.util.concurrency.SynchronizedClearableLazy._get_value_$lambda$1$lambda$0(SynchronizedClearableLazy.kt:41)
	at java.base/java.util.concurrent.atomic.AtomicReference.updateAndGet(AtomicReference.java:210)
	at com.intellij.util.concurrency.SynchronizedClearableLazy.getValue(SynchronizedClearableLazy.kt:40)
	at com.intellij.ui.scale.JBUIScale.sysScale(JBUIScale.kt:307)
	at com.intellij.ui.scale.ScaleContext.<init>(ScaleContext.kt:83)
	at com.intellij.ui.scale.ScaleContext$Companion.create(ScaleContext.kt:80)
	at com.intellij.ui.icons.CachedImageIcon.<init>(CachedImageIcon.kt:75)
	at com.intellij.ui.icons.CachedImageIcon.<init>(CachedImageIcon.kt:101)
	at com.intellij.ui.icons.CoreIconManager.loadRasterizedIcon(CoreIconManager.kt:107)
	at com.intellij.icons.AllIcons.load(AllIcons.java:17)
	at com.intellij.icons.AllIcons.<clinit>(AllIcons.java:698)
	at com.intellij.icons.AllIcons$General.<clinit>(AllIcons.java:427)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.settings.options.types.TemplateOption.<init>(TemplateOption.kt:43)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.settings.options.types.TemplateOptionKt.template(TemplateOption.kt:39)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.settings.impl.ApplicationSettingsImpl.<init>(ApplicationSettingsImpl.kt:59)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at com.intellij.serviceContainer.ConstructorInjectionKt.instantiateUsingPicoContainer(constructorInjection.kt:63)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClassWithConstructorInjection(ComponentManagerImpl.kt:1011)
	at com.intellij.serviceContainer.ServiceComponentAdapter.createAndInitialize(ServiceComponentAdapter.kt:47)
	at com.intellij.serviceContainer.ServiceComponentAdapter.doCreateInstance(ServiceComponentAdapter.kt:43)
	at com.intellij.serviceContainer.BaseComponentAdapter.doCreateInstance(BaseComponentAdapter.kt:158)
	at com.intellij.serviceContainer.BaseComponentAdapter.createInstance(BaseComponentAdapter.kt:137)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance(BaseComponentAdapter.kt:94)
	at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:676)
	at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:630)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.settings.ApplicationSettingsKt.getSettings(ApplicationSettings.kt:84)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.time.TimeService.load(TimeService.kt:212)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.time.TimePreloadingActivity.preload(TimePreloadingActivity.kt:25)
	at com.intellij.openapi.application.PreloadingActivity$execute$2.invoke(PreloadingActivity.kt:15)
	at com.intellij.openapi.application.PreloadingActivity$execute$2.invoke(PreloadingActivity.kt:14)
	at com.intellij.openapi.progress.CoroutinesKt.blockingContext(coroutines.kt:248)
	at com.intellij.openapi.progress.CoroutinesKt.blockingContext(coroutines.kt:199)
	at com.intellij.openapi.application.PreloadingActivity.execute$suspendImpl(PreloadingActivity.kt:14)
	at com.intellij.openapi.application.PreloadingActivity.execute(PreloadingActivity.kt)
	at com.intellij.ide.bootstrap.AppServicePreloadingKt.executePreloadActivity(appServicePreloading.kt:167)
	at com.intellij.ide.bootstrap.AppServicePreloadingKt.access$executePreloadActivity(appServicePreloading.kt:1)
	at com.intellij.ide.bootstrap.AppServicePreloadingKt$postAppRegistered$4$1$1.invokeSuspend(appServicePreloading.kt:155)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
```

and  

```
Unhandled exception in [StandaloneCoroutine{Cancelling}@5fe0a784, Dispatchers.Default]
  
  java.net.SocketException: ; errno=111
at org.newsclub.net.unix.NativeUnixSocket.connect(Native Method)
at org.newsclub.net.unix.AFSocketImpl.connect0(AFSocketImpl.java:372)
at org.newsclub.net.unix.AFSocket.connect0(AFSocket.java:265)
at org.newsclub.net.unix.AFSocket.connect(AFSocket.java:234)
at org.newsclub.net.unix.AFSocket.connect(AFSocket.java:229)
at dev.cbyrne.kdiscordipc.core.socket.impl.UnixSocket.connect(UnixSocket.kt:19)
at dev.cbyrne.kdiscordipc.core.socket.handler.SocketHandler.connect(SocketHandler.kt:59)
at dev.cbyrne.kdiscordipc.KDiscordIPC.connect(KDiscordIPC.kt:83)
at dev.cbyrne.kdiscordipc.KDiscordIPC.connect$default(KDiscordIPC.kt:76)
at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.connection.DiscordIpcConnection$connect$2.invokeSuspend(DiscordIpcConnection.kt:59)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelled}@5fe0a784, Dispatchers.Default]
```

I am running on Arch Linux x86_64, latest available kernel and no updates available right now.

> My Discord is already open when I'm opening IntelliJ.
> Discord isn't installed with `Flatpak` but with `Pacman`. 
> InteliJ is installed with the Jetbrains Toolkit, which himself is installed with `yay`

Does anyone faces the same issue as me and know a fix ? Thanks in advance.

**Comment by xenedium** [comment]
Same issue here on Arch Linux with Goland

**Comment by EinfxchFinn** [comment]
Same with  v1.12.0 on Arch Linux

**Comment by ghost** [comment]
Same issue on v1.12.0, also using Arch Linux and IntelliJ 2023.2.5 Ultimate (Build #IU-232.10227.8) with runtime version 17.0.9-b1000.46 amd64 (if that bit's relevant)

**Comment by MCUxDaredevil** [comment]
I've had similar issues using it on both Linux and Windows
It doesn't stop anything from working I think, the status still shows and updates on Discord
I think it has something to do with having Discord open at startup when the plugin loads?
It would be cool if this error doesn't pop up every time I start the IDE without Discord open.

It would be helpful if anyone else can also confirm this theory
Just have Discord open and then start the IDE, does it still show the error?

**Comment by AzhamProdLive** [comment]
> I've had similar issues using it on both Linux and Windows
> It doesn't stop anything from working I think, the status still shows and updates on Discord
> I think it has something to do with having Discord open at startup when the plugin loads?
> It would be cool if this error doesn't pop up every time I start the IDE without Discord open.
> 
> It would be helpful if anyone else can also confirm this theory
> Just have Discord open and then start the IDE, does it still show the error?

Yes it does, Discord's open when I start the IDE and the error appears
