### ISSUE TITLE
Error en starting

### ISSUE THREAD

**Issue by fuzeblocks** [Almighty-Alpaca/JetBrains-Discord-Integration#376]
java.lang.Throwable: IPC error: ErrorEventData(code=4000, message=child "activity" fails because [child "assets" fails because [child "large_text" fails because ["large_text" is not allowed to be empty]]])
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:370)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.connection.DiscordIpcConnection.onError(DiscordIpcConnection.kt:133)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.connection.DiscordIpcConnection.access$onError(DiscordIpcConnection.kt:39)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.connection.DiscordIpcConnection$ipcClient$1$1.invokeSuspend$onError(DiscordIpcConnection.kt:47)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.connection.DiscordIpcConnection$ipcClient$1$1.access$invokeSuspend$onError(DiscordIpcConnection.kt)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.connection.DiscordIpcConnection$ipcClient$1$1$2.invoke(DiscordIpcConnection.kt:47)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.connection.DiscordIpcConnection$ipcClient$1$1$2.invoke(DiscordIpcConnection.kt:47)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.connection.DiscordIpcConnection$ipcClient$1$1$invokeSuspend$$inlined$onEvent$4$1.invokeSuspend(KDiscordIPC.kt:103)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:100)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)

**Comment by Azn9** [comment]
Hey, I made a fork of this plugin with a fix for that : https://github.com/Azn9/Jetbrains-Discord-Integration

**Comment by fuzeblocks** [comment]
Hi 👋, it's work thank you :)

Le sam. 23 sept. 2023 à 01:48, Axel Joly ***@***.***> a
écrit :

**Comment by alan-leal** [comment]
Hello @Azn9 , this fixed my same error as well. Thank you!
However, I was wondering, out of curiosity, if you could shed some light on what exactly this error was stemming from in the project build and how you managed to fix it?

**Comment by Azn9** [comment]
@alan-leal for this error, there was just an issue where if no text was provided for the icons, it would be set as null. Just setting it to a blank string prevents the issue.
Note that I didn't fixed it by myself, I just copied #289 into my fork and merged it.
