### ISSUE TITLE
Random error: Unhandled exception in [StandaloneCoroutine{Cancelling}@936b01b, Dispatchers.Default]

### ISSUE THREAD

**Issue by luimen6** [Almighty-Alpaca/JetBrains-Discord-Integration#381]
Unhandled exception in [StandaloneCoroutine{Cancelling}@936b01b, Dispatchers.Default]
  
  org.newsclub.net.unix.SocketClosedException: Not open
at org.newsclub.net.unix.AFCore.validFdOrException(AFCore.java:86)
at org.newsclub.net.unix.AFSocketImpl.getInputStream(AFSocketImpl.java:405)
at org.newsclub.net.unix.AFSocket.getInputStream(AFSocket.java:502)
at dev.cbyrne.kdiscordipc.core.socket.impl.UnixSocket.readBytes(UnixSocket.kt:38)
at dev.cbyrne.kdiscordipc.core.socket.impl.UnixSocket.readLittleEndianInt(UnixSocket.kt:34)
at dev.cbyrne.kdiscordipc.core.socket.impl.UnixSocket.read(UnixSocket.kt:24)
at dev.cbyrne.kdiscordipc.core.socket.handler.SocketHandler$events$1.invokeSuspend(SocketHandler.kt:35)
at dev.cbyrne.kdiscordipc.core.socket.handler.SocketHandler$events$1.invoke(SocketHandler.kt)
at dev.cbyrne.kdiscordipc.core.socket.handler.SocketHandler$events$1.invoke(SocketHandler.kt)
at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:230)
at kotlinx.coroutines.flow.internal.ChannelFlowOperatorImpl.flowCollect(ChannelFlow.kt:195)
at kotlinx.coroutines.flow.internal.ChannelFlowOperator.collectTo$suspendImpl(ChannelFlow.kt:157)
at kotlinx.coroutines.flow.internal.ChannelFlowOperator.collectTo(ChannelFlow.kt)
at kotlinx.coroutines.flow.internal.ChannelFlow$collectToFun$1.invokeSuspend(ChannelFlow.kt:60)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:100)
at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelled}@936b01b, Dispatchers.Default]

**Comment by itsTyrion** [comment]
Project is abandoned, here's a maintained fork https://github.com/Azn9/JetBrains-Discord-Integration
