### ISSUE TITLE
error: Unhandled exception in [StandaloneCoroutine{Cancelling}@1db3dcd4, Dispatchers.Default]

### ISSUE THREAD

**Issue by mzulfanw** [Almighty-Alpaca/JetBrains-Discord-Integration#383]
Unhandled exception in [StandaloneCoroutine{Cancelling}@1db3dcd4, Dispatchers.Default]
  
  java.net.SocketException: Connection refused; errno=61
at org.newsclub.net.unix.NativeUnixSocket.connect(Native Method)
at org.newsclub.net.unix.AFSocketImpl.connect0(AFSocketImpl.java:372)
at org.newsclub.net.unix.AFSocket.connect0(AFSocket.java:265)
at org.newsclub.net.unix.AFSocket.connect(AFSocket.java:234)
at org.newsclub.net.unix.AFSocket.connect(AFSocket.java:229)
at dev.cbyrne.kdiscordipc.core.socket.impl.UnixSocket.connect(UnixSocket.kt:19)
at dev.cbyrne.kdiscordipc.core.socket.handler.SocketHandler.connect(SocketHandler.kt:59)
at dev.cbyrne.kdiscordipc.KDiscordIPC.connect(KDiscordIPC.kt:83)
at dev.cbyrne.kdiscordipc.KDiscordIPC.connect$default(KDiscordIPC.kt:76)
at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.connection.DiscordIpcConnection$connect$2.invokeSuspend(DiscordIpcConnection.kt:59)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelled}@1db3dcd4, Dispatchers.Default]

**Comment by itsTyrion** [comment]
Project is abandoned, here's a maintained fork https://github.com/Azn9/JetBrains-Discord-Integration

**Comment by mzulfanw** [comment]
thank you for the information
