### ISSUE TITLE
Unhandled exception in [StandaloneCoroutine{Cancelling}@2594ae2c, Dispatchers.Default]

### ISSUE THREAD

**Issue by AndreyGP** [Almighty-Alpaca/JetBrains-Discord-Integration#384]
Good day!
```
IntelliJ IDEA 2023.1.5 (Ultimate Edition)
Build #IU-231.9392.1, built on July 25, 2023
Licensed to kiddy inseams
You have a perpetual fallback license for this version.
Subscription is active until August 1, 2025.
Runtime version: 17.0.7+10-b829.16 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 16
Non-Bundled Plugins:
    lermitage.intellij.extratci (1.27.0)
    https://github.com/DUNNIK (1.7)
    com.intellij.plugins.xwinkeymap (211.4961.30)
    com.andrey4623.rainbowcsv (2.0.2)
    com.intellij.properties.bundle.editor (231.8109.91)
    com.intellij.jira (4.5.0)
    com.jetbrains.jax.ws (231.8109.90)
    MavenRunHelper (4.26.0-IJ2022.2)
    com.almightyalpaca.intellij.plugins.discord (1.11.0)
    izhangzhihao.rainbow.brackets.lite (1.1.0)
    com.mallowigi (90.0.0)

Kotlin: 231-1.8.21-IJ9392.1
```
Exception info:
```
Unhandled exception in [StandaloneCoroutine{Cancelling}@2594ae2c, Dispatchers.Default]

dev.cbyrne.kdiscordipc.core.error.ConnectionError$NoIPCFile: Failed to find an IPC file. Is Discord open? Is this application allowed to access temporary files?
	at dev.cbyrne.kdiscordipc.core.error.ConnectionError$NoIPCFile.<clinit>(ConnectionError.kt)
	at dev.cbyrne.kdiscordipc.core.socket.handler.SocketHandler.findIPCFile(SocketHandler.kt:95)
	at dev.cbyrne.kdiscordipc.core.socket.handler.SocketHandler.findIPCFile(SocketHandler.kt:99)
	at dev.cbyrne.kdiscordipc.core.socket.handler.SocketHandler.findIPCFile(SocketHandler.kt:99)
	at dev.cbyrne.kdiscordipc.core.socket.handler.SocketHandler.findIPCFile(SocketHandler.kt:99)
	at dev.cbyrne.kdiscordipc.core.socket.handler.SocketHandler.findIPCFile(SocketHandler.kt:99)
	at dev.cbyrne.kdiscordipc.core.socket.handler.SocketHandler.findIPCFile(SocketHandler.kt:99)
	at dev.cbyrne.kdiscordipc.core.socket.handler.SocketHandler.findIPCFile(SocketHandler.kt:99)
	at dev.cbyrne.kdiscordipc.core.socket.handler.SocketHandler.findIPCFile(SocketHandler.kt:99)
	at dev.cbyrne.kdiscordipc.core.socket.handler.SocketHandler.findIPCFile(SocketHandler.kt:99)
	at dev.cbyrne.kdiscordipc.core.socket.handler.SocketHandler.findIPCFile(SocketHandler.kt:99)
	at dev.cbyrne.kdiscordipc.core.socket.handler.SocketHandler.findIPCFile(SocketHandler.kt:99)
	at dev.cbyrne.kdiscordipc.core.socket.handler.SocketHandler.connect(SocketHandler.kt:59)
	at dev.cbyrne.kdiscordipc.KDiscordIPC.connect(KDiscordIPC.kt:83)
	at dev.cbyrne.kdiscordipc.KDiscordIPC.connect$default(KDiscordIPC.kt:76)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.connection.DiscordIpcConnection$connect$2.invokeSuspend(DiscordIpcConnection.kt:59)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelled}@2594ae2c, Dispatchers.Default]
```
Thank You so mach!

**Comment by itsTyrion** [comment]
Project is abandoned, here's a maintained fork https://github.com/Azn9/JetBrains-Discord-Integration
