### ISSUE TITLE
Exception when log file was opened

### ISSUE THREAD

**Issue by Wixty** [Almighty-Alpaca/JetBrains-Discord-Integration#61]
After last update to v1.0.0 plugin periodically throws an exception for log files.
I also use the ideolog extension, which highlights the text. Maybe there are conflicts?
Example of problematic log file:
```
{"message":"some info message","level":"info","timestamp":"2019-08-15T12:36:14.261Z"}
{"message":"some error message","level":"error","timestamp":"2019-08-15T12:58:17.857Z"}
...
```
Stack trace for exception:
```
java.nio.file.InvalidPathException: Illegal char <<> at index 0: <74cffee0-dc06-4d8b-916f-713aa3a005d4>/**/**/**.log
	at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
	at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:229)
	at java.base/java.nio.file.Path.of(Path.java:147)
	at java.base/java.nio.file.Paths.get(Paths.java:69)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.data.FileData$relativePath$2.invoke(FileData.kt:88)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.data.FileData$relativePath$2.invoke(FileData.kt:31)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.dependencies.kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.data.FileData.getRelativePath(FileData.kt)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.data.FileData$relativePathSane$2.invoke(FileData.kt:40)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.data.FileData$relativePathSane$2.invoke(FileData.kt:31)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.dependencies.kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.data.FileData.getRelativePathSane(FileData.kt)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.data.FileData.getField(FileData.kt:55)
	at com.almightyalpaca.jetbrains.plugins.discord.shared.source.abstract.AbstractLanguageMap.findLanguage(AbstractLanguageMap.kt:30)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.renderer.RenderContext$match$2.invoke(RenderContext.kt:36)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.renderer.RenderContext$match$2.invoke(RenderContext.kt:27)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.dependencies.kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.renderer.RenderContext.getMatch(RenderContext.kt)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.settings.values.PresenceIcon$FILE.getResult(PresenceIcon.kt:31)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.settings.values.PresenceIcon.get(PresenceIcon.kt:40)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.renderer.Renderer$render$1.invoke(Renderer.kt:57)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.renderer.Renderer$render$1.invoke(Renderer.kt:23)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.RichPresence.<init>(RichPresence.kt:45)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.renderer.Renderer.render(Renderer.kt:39)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.renderer.FileRenderer.render(FileRenderer.kt:22)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.renderer.Renderer.render(Renderer.kt:24)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.impl.RichPresenceRenderServiceImpl$render$1.invokeSuspend(RichPresenceRenderServiceImpl.kt:93)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.dependencies.kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.dependencies.kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:238)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.dependencies.kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.dependencies.kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.dependencies.kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742)
```

**Comment by Almighty-Alpaca** [comment]
Do you open any special editor tab when that happens? Example for this would be db connection or a file that doesn't exist on your file system.

**Comment by Wixty** [comment]
Good tip! The error appears only when opening log files from a remote host.

**Comment by Almighty-Alpaca** [comment]
Can you give me the name of the plugin you use for that?

**Comment by Wixty** [comment]
This is built-in functionality:
https://www.jetbrains.com/help/phpstorm/2019.2/remote-host-tool-window.html
Ideolog for log formatting and highlighting:
https://github.com/JetBrains/ideolog

**Comment by Wixty** [comment]
Bundled plugin name: Remote Hosts Access

**Comment by Almighty-Alpaca** [comment]
Thanks, will take a look at that :+1:
