### ISSUE TITLE
[Exception] when closing a project.

### ISSUE THREAD

**Issue by samomar** [Almighty-Alpaca/JetBrains-Discord-Integration#63]
```java
java.lang.AssertionError: Already disposed: Project (Disposed) facebook_core
	at com.intellij.openapi.components.impl.ComponentManagerImpl.lambda$throwAlreadyDisposed$1(ComponentManagerImpl.java:286)
	at com.intellij.openapi.application.ReadAction.lambda$run$1(ReadAction.java:53)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:932)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:57)
	at com.intellij.openapi.application.ReadAction.run(ReadAction.java:53)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.throwAlreadyDisposed(ComponentManagerImpl.java:284)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.getPicoContainer(ComponentManagerImpl.java:277)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.getComponent(ComponentManagerImpl.java:182)
	at com.intellij.openapi.fileEditor.FileEditorManager.getInstance(FileEditorManager.java:21)
	at com.intellij.openapi.fileEditor.impl.UniqueVFilePathBuilderImpl.filesWithTheSameName(UniqueVFilePathBuilderImpl.java:134)
	at com.intellij.openapi.fileEditor.impl.UniqueVFilePathBuilderImpl.getUniqueVirtualFileNameBuilder(UniqueVFilePathBuilderImpl.java:110)
	at com.intellij.openapi.fileEditor.impl.UniqueVFilePathBuilderImpl.getUniqueVirtualFilePath(UniqueVFilePathBuilderImpl.java:70)
	at com.intellij.openapi.fileEditor.impl.UniqueVFilePathBuilderImpl.getUniqueVirtualFilePathWithinOpenedFileEditors(UniqueVFilePathBuilderImpl.java:50)
	at com.intellij.openapi.fileEditor.impl.UniqueNameEditorTabTitleProvider.getEditorTabTitle(UniqueNameEditorTabTitleProvider.java:29)
	at com.intellij.openapi.fileEditor.impl.EditorTabTitleProvider.getEditorTabTitle(EditorTabTitleProvider.java:21)
	at com.intellij.openapi.fileEditor.impl.EditorTabPresentationUtil.getEditorTabTitle(EditorTabPresentationUtil.java:18)
	at com.intellij.openapi.fileEditor.impl.EditorTabPresentationUtil.getUniqueEditorTabTitle(EditorTabPresentationUtil.java:29)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.data.FileData$uniqueName$2$1.compute(FileData.kt:44)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.data.FileData$uniqueName$2$1.compute(FileData.kt:31)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:922)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.data.FileData$uniqueName$2.invoke(FileData.kt:44)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.data.FileData$uniqueName$2.invoke(FileData.kt:31)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.dependencies.kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.data.FileData.getUniqueName(FileData.kt)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.settings.values.PresenceLine$FILE_NAME_PATH.getResult(PresenceLine.kt:61)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.settings.values.PresenceLine.get(PresenceLine.kt:72)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.renderer.Renderer$render$1.invoke(Renderer.kt:46)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.renderer.Renderer$render$1.invoke(Renderer.kt:23)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.RichPresence.<init>(RichPresence.kt:45)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.renderer.Renderer.render(Renderer.kt:39)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.renderer.FileRenderer.render(FileRenderer.kt:22)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.renderer.Renderer.render(Renderer.kt:24)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.impl.RichPresenceRenderServiceImpl$render$1.invokeSuspend(RichPresenceRenderServiceImpl.kt:93)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.dependencies.kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.dependencies.kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:238)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.dependencies.kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.dependencies.kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.dependencies.kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742)
```

**Comment by Almighty-Alpaca** [comment]
Sounds like a race condition, should be easy to fix though.

**Comment by Morilli** [comment]
Just got the same issue. Thought I'd mention it.

**Comment by liach** [comment]
Still happens in 1.1.0.

Stacktrace and induced.txt: https://gist.github.com/907f7776d9a3f51888114594cd01a8d8

**Comment by Almighty-Alpaca** [comment]
I guess I'll have to look at it again...

**Comment by liach** [comment]
Another stacktrace here.
https://gist.github.com/64e97d5c4dfaf9e88acbdafd48a68955
I was closing the "runorama" project and opening another project in the same window when the index was still updating in Intellij Idea.

**Comment by InfRandomness** [comment]
Just had 

`
java.lang.Throwable: Directory index is already disposed for Project (name=Beta, containerState=DISPOSE_COMPLETED, componentStore=/home/ir/Documents/Developpement/Kotlin/MG/Web/Beta) 
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:145)
	at com.intellij.openapi.roots.impl.DirectoryIndexImpl.checkAvailability(DirectoryIndexImpl.java:194)
	at com.intellij.openapi.roots.impl.DirectoryIndexImpl.getInfoForFile(DirectoryIndexImpl.java:135)
	at com.intellij.openapi.roots.impl.ProjectFileIndexFacade.isInProjectScope(ProjectFileIndexFacade.java:103)
	at com.intellij.psi.search.ProjectScopeImpl.contains(ProjectScopeImpl.java:38)
	at com.intellij.psi.search.GlobalSearchScope.accept(GlobalSearchScope.java:71)
	at com.intellij.util.indexing.FileBasedIndexImpl.lambda$processValuesInScope$14(FileBasedIndexImpl.java:962)
	at com.intellij.util.indexing.FileBasedIndexImpl.lambda$processValueIterator$15(FileBasedIndexImpl.java:985)
	at com.intellij.util.indexing.FileBasedIndexImpl.lambda$null$11(FileBasedIndexImpl.java:910)
	at com.intellij.util.ConcurrencyUtil.withLock(ConcurrencyUtil.java:242)
	at com.intellij.util.indexing.FileBasedIndexImpl.lambda$processExceptions$12(FileBasedIndexImpl.java:910)
	at com.intellij.util.indexing.IndexAccessValidator.validate(IndexAccessValidator.java:43)
	at com.intellij.util.indexing.FileBasedIndexImpl.processExceptions(FileBasedIndexImpl.java:910)
	at com.intellij.util.indexing.FileBasedIndexImpl.processValueIterator(FileBasedIndexImpl.java:984)
	at com.intellij.util.indexing.FileBasedIndexImpl.processValuesInScope(FileBasedIndexImpl.java:955)
	at com.intellij.util.indexing.FileBasedIndexImpl.processValues(FileBasedIndexImpl.java:852)
	at com.intellij.psi.search.FileNameIndexServiceImpl.getVirtualFilesByName(FileNameIndexServiceImpl.java:27)
	at com.intellij.psi.search.FilenameIndex.getVirtualFilesByName(FilenameIndex.java:51)
	at com.intellij.openapi.fileEditor.impl.UniqueVFilePathBuilderImpl.filesWithTheSameName(UniqueVFilePathBuilderImpl.java:131)
	at com.intellij.openapi.fileEditor.impl.UniqueVFilePathBuilderImpl.getUniqueVirtualFileNameBuilder(UniqueVFilePathBuilderImpl.java:110)
	at com.intellij.openapi.fileEditor.impl.UniqueVFilePathBuilderImpl.getUniqueVirtualFilePath(UniqueVFilePathBuilderImpl.java:70)
	at com.intellij.openapi.fileEditor.impl.UniqueVFilePathBuilderImpl.getUniqueVirtualFilePath(UniqueVFilePathBuilderImpl.java:38)
	at com.intellij.openapi.fileEditor.impl.UniqueVFilePathBuilderImpl.getUniqueVirtualFilePath(UniqueVFilePathBuilderImpl.java:44)
	at com.intellij.openapi.fileEditor.impl.EditorTabPresentationUtil.getUniqueEditorTabTitle(EditorTabPresentationUtil.java:31)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.data.FileData$uniqueName$2$1.compute(FileData.kt:44)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.data.FileData$uniqueName$2$1.compute(FileData.kt:31)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:811)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.data.FileData$uniqueName$2.invoke(FileData.kt:44)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.data.FileData$uniqueName$2.invoke(FileData.kt:31)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.dependencies.kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.data.FileData.getUniqueName(FileData.kt)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.settings.values.PresenceLine$FILE_NAME_PATH.getResult(PresenceLine.kt:61)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.settings.values.PresenceLine.get(PresenceLine.kt:72)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.renderer.Renderer$render$1.invoke(Renderer.kt:47)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.renderer.Renderer$render$1.invoke(Renderer.kt:24)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.RichPresence.<init>(RichPresence.kt:46)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.renderer.Renderer.render(Renderer.kt:40)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.renderer.FileRenderer.render(FileRenderer.kt:22)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.renderer.Renderer.render(Renderer.kt:25)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.impl.RichPresenceRenderServiceImpl$render$1.invokeSuspend(RichPresenceRenderServiceImpl.kt:93)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.dependencies.kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.dependencies.kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.dependencies.kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.dependencies.kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.dependencies.kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:740)
`

and a bunch of this 

`
Following exceptions happened soon after this one, most probably they are induced.


2019-12-15T15:36:17.973
java.lang.Throwable: Directory index is already disposed for Project (name=Beta, containerState=DISPOSE_COMPLETED, componentStore=/home/ir/Documents/Developpement/Kotlin/MG/Web/Beta) 
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:145)
	at com.intellij.openapi.roots.impl.DirectoryIndexImpl.checkAvailability(DirectoryIndexImpl.java:194)
	at com.intellij.openapi.roots.impl.DirectoryIndexImpl.getInfoForFile(DirectoryIndexImpl.java:135)
	at com.intellij.openapi.roots.impl.ProjectFileIndexFacade.isInProjectScope(ProjectFileIndexFacade.java:103)
	at com.intellij.psi.search.ProjectScopeImpl.contains(ProjectScopeImpl.java:38)
	at com.intellij.psi.search.GlobalSearchScope.accept(GlobalSearchScope.java:71)
	at com.intellij.util.indexing.FileBasedIndexImpl.lambda$processValuesInScope$14(FileBasedIndexImpl.java:962)
	at com.intellij.util.indexing.FileBasedIndexImpl.lambda$processValueIterator$15(FileBasedIndexImpl.java:985)
	at com.intellij.util.indexing.FileBasedIndexImpl.lambda$null$11(FileBasedIndexImpl.java:910)
	at com.intellij.util.ConcurrencyUtil.withLock(ConcurrencyUtil.java:242)
	at com.intellij.util.indexing.FileBasedIndexImpl.lambda$processExceptions$12(FileBasedIndexImpl.java:910)
	at com.intellij.util.indexing.IndexAccessValidator.validate(IndexAccessValidator.java:43)
	at com.intellij.util.indexing.FileBasedIndexImpl.processExceptions(FileBasedIndexImpl.java:910)
	at com.intellij.util.indexing.FileBasedIndexImpl.processValueIterator(FileBasedIndexImpl.java:984)
	at com.intellij.util.indexing.FileBasedIndexImpl.processValuesInScope(FileBasedIndexImpl.java:955)
	at com.intellij.util.indexing.FileBasedIndexImpl.processValues(FileBasedIndexImpl.java:852)
	at com.intellij.psi.search.FileNameIndexServiceImpl.getVirtualFilesByName(FileNameIndexServiceImpl.java:27)
	at com.intellij.psi.search.FilenameIndex.getVirtualFilesByName(FilenameIndex.java:51)
	at com.intellij.openapi.fileEditor.impl.UniqueVFilePathBuilderImpl.filesWithTheSameName(UniqueVFilePathBuilderImpl.java:131)
	at com.intellij.openapi.fileEditor.impl.UniqueVFilePathBuilderImpl.getUniqueVirtualFileNameBuilder(UniqueVFilePathBuilderImpl.java:110)
	at com.intellij.openapi.fileEditor.impl.UniqueVFilePathBuilderImpl.getUniqueVirtualFilePath(UniqueVFilePathBuilderImpl.java:70)
	at com.intellij.openapi.fileEditor.impl.UniqueVFilePathBuilderImpl.getUniqueVirtualFilePath(UniqueVFilePathBuilderImpl.java:38)
	at com.intellij.openapi.fileEditor.impl.UniqueVFilePathBuilderImpl.getUniqueVirtualFilePath(UniqueVFilePathBuilderImpl.java:44)
	at com.intellij.openapi.fileEditor.impl.EditorTabPresentationUtil.getUniqueEditorTabTitle(EditorTabPresentationUtil.java:31)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.data.FileData$uniqueName$2$1.compute(FileData.kt:44)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.data.FileData$uniqueName$2$1.compute(FileData.kt:31)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:811)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.data.FileData$uniqueName$2.invoke(FileData.kt:44)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.data.FileData$uniqueName$2.invoke(FileData.kt:31)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.dependencies.kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.data.FileData.getUniqueName(FileData.kt)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.settings.values.PresenceLine$FILE_NAME_PATH.getResult(PresenceLine.kt:61)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.settings.values.PresenceLine.get(PresenceLine.kt:72)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.renderer.Renderer$render$1.invoke(Renderer.kt:47)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.renderer.Renderer$render$1.invoke(Renderer.kt:24)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.RichPresence.<init>(RichPresence.kt:46)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.renderer.Renderer.render(Renderer.kt:40)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.renderer.FileRenderer.render(FileRenderer.kt:22)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.renderer.Renderer.render(Renderer.kt:25)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.impl.RichPresenceRenderServiceImpl$render$1.invokeSuspend(RichPresenceRenderServiceImpl.kt:93)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.dependencies.kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.dependencies.kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.dependencies.kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.dependencies.kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.dependencies.kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:740)
`

**Comment by Almighty-Alpaca** [comment]
Small status update: A fix is being tested for this but due to the random nature of this bug it's very hard to validate that I've covered all cases this time. I'll hopefully push this to production soon:tm:.

**Comment by yeSpud** [comment]
Im also having this issue now, but I assume that its just about fixed

Heres the stack-trace regardless

```
java.lang.AssertionError: Already disposed: Project (Disposed) Visualizer-framework
	at com.intellij.openapi.components.impl.ComponentManagerImpl.lambda$throwAlreadyDisposed$1(ComponentManagerImpl.java:286)
	at com.intellij.openapi.application.ReadAction.lambda$run$1(ReadAction.java:53)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:932)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:57)
	at com.intellij.openapi.application.ReadAction.run(ReadAction.java:53)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.throwAlreadyDisposed(ComponentManagerImpl.java:284)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.getPicoContainer(ComponentManagerImpl.java:277)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.getComponent(ComponentManagerImpl.java:182)
	at com.intellij.openapi.fileEditor.FileEditorManager.getInstance(FileEditorManager.java:21)
	at com.intellij.openapi.fileEditor.impl.UniqueVFilePathBuilderImpl.filesWithTheSameName(UniqueVFilePathBuilderImpl.java:134)
	at com.intellij.openapi.fileEditor.impl.UniqueVFilePathBuilderImpl.getUniqueVirtualFileNameBuilder(UniqueVFilePathBuilderImpl.java:110)
	at com.intellij.openapi.fileEditor.impl.UniqueVFilePathBuilderImpl.getUniqueVirtualFilePath(UniqueVFilePathBuilderImpl.java:70)
	at com.intellij.openapi.fileEditor.impl.UniqueVFilePathBuilderImpl.getUniqueVirtualFilePathWithinOpenedFileEditors(UniqueVFilePathBuilderImpl.java:50)
	at com.intellij.openapi.fileEditor.impl.UniqueNameEditorTabTitleProvider.getEditorTabTitle(UniqueNameEditorTabTitleProvider.java:29)
	at com.intellij.openapi.fileEditor.impl.EditorTabTitleProvider.getEditorTabTitle(EditorTabTitleProvider.java:21)
	at com.intellij.openapi.fileEditor.impl.EditorTabPresentationUtil.getEditorTabTitle(EditorTabPresentationUtil.java:18)
	at com.intellij.openapi.fileEditor.impl.EditorTabPresentationUtil.getUniqueEditorTabTitle(EditorTabPresentationUtil.java:29)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.data.FileData$uniqueName$2$1.compute(FileData.kt:44)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.data.FileData$uniqueName$2$1.compute(FileData.kt:31)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:922)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.data.FileData$uniqueName$2.invoke(FileData.kt:44)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.data.FileData$uniqueName$2.invoke(FileData.kt:31)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.dependencies.kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.data.FileData.getUniqueName(FileData.kt)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.settings.values.PresenceLine$FILE_NAME_PATH.getResult(PresenceLine.kt:61)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.settings.values.PresenceLine.get(PresenceLine.kt:72)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.renderer.Renderer$render$1.invoke(Renderer.kt:47)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.renderer.Renderer$render$1.invoke(Renderer.kt:24)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.RichPresence.<init>(RichPresence.kt:46)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.renderer.Renderer.render(Renderer.kt:40)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.renderer.FileRenderer.render(FileRenderer.kt:22)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.renderer.Renderer.render(Renderer.kt:25)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.impl.RichPresenceRenderServiceImpl$render$1.invokeSuspend(RichPresenceRenderServiceImpl.kt:93)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.dependencies.kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.dependencies.kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.dependencies.kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.dependencies.kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.dependencies.kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:740)
```

**Comment by Almighty-Alpaca** [comment]
Finally published the fix, will be available after the weekend.
