### ISSUE TITLE
Exception occoring in Pycharm Professional

### ISSUE THREAD

**Issue by ZusorCode** [Almighty-Alpaca/JetBrains-Discord-Integration#65]
I don't know why I'm getting this exception, I'm using v1.0.1 and the latest Pycharm.
Here's the stacktrace:

```
java.lang.AssertionError: Already disposed: Project (Disposed) Portfolio
	at com.intellij.openapi.components.impl.ComponentManagerImpl.lambda$throwAlreadyDisposed$1(ComponentManagerImpl.java:286)
	at com.intellij.openapi.application.ReadAction.lambda$run$1(ReadAction.java:53)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:932)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:57)
	at com.intellij.openapi.application.ReadAction.run(ReadAction.java:53)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.throwAlreadyDisposed(ComponentManagerImpl.java:284)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.getPicoContainer(ComponentManagerImpl.java:277)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.getComponent(ComponentManagerImpl.java:182)
	at com.intellij.openapi.fileEditor.FileEditorManager.getInstance(FileEditorManager.java:21)
	at com.intellij.openapi.fileEditor.impl.UniqueVFilePathBuilderImpl.filesWithTheSameName(UniqueVFilePathBuilderImpl.java:134)
	at com.intellij.openapi.fileEditor.impl.UniqueVFilePathBuilderImpl.getUniqueVirtualFileNameBuilder(UniqueVFilePathBuilderImpl.java:110)
	at com.intellij.openapi.fileEditor.impl.UniqueVFilePathBuilderImpl.getUniqueVirtualFilePath(UniqueVFilePathBuilderImpl.java:70)
	at com.intellij.openapi.fileEditor.impl.UniqueVFilePathBuilderImpl.getUniqueVirtualFilePathWithinOpenedFileEditors(UniqueVFilePathBuilderImpl.java:50)
	at com.intellij.openapi.fileEditor.impl.UniqueNameEditorTabTitleProvider.getEditorTabTitle(UniqueNameEditorTabTitleProvider.java:29)
	at com.intellij.openapi.fileEditor.impl.EditorTabTitleProvider.getEditorTabTitle(EditorTabTitleProvider.java:21)
	at com.intellij.openapi.fileEditor.impl.EditorTabPresentationUtil.getEditorTabTitle(EditorTabPresentationUtil.java:18)
	at com.intellij.openapi.fileEditor.impl.EditorTabPresentationUtil.getUniqueEditorTabTitle(EditorTabPresentationUtil.java:29)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.data.FileData$uniqueName$2$1.compute(FileData.kt:44)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.data.FileData$uniqueName$2$1.compute(FileData.kt:31)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:922)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.data.FileData$uniqueName$2.invoke(FileData.kt:44)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.data.FileData$uniqueName$2.invoke(FileData.kt:31)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.dependencies.kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.data.FileData.getUniqueName(FileData.kt)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.settings.values.PresenceLine$FILE_NAME_PATH.getResult(PresenceLine.kt:61)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.settings.values.PresenceLine.get(PresenceLine.kt:72)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.renderer.Renderer$render$1.invoke(Renderer.kt:46)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.renderer.Renderer$render$1.invoke(Renderer.kt:23)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.RichPresence.<init>(RichPresence.kt:45)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.renderer.Renderer.render(Renderer.kt:39)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.renderer.FileRenderer.render(FileRenderer.kt:22)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.renderer.Renderer.render(Renderer.kt:24)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.impl.RichPresenceRenderServiceImpl$render$1.invokeSuspend(RichPresenceRenderServiceImpl.kt:93)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.dependencies.kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.dependencies.kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:238)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.dependencies.kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.dependencies.kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.dependencies.kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742)
```
Let me know if you have any questions

**Comment by Almighty-Alpaca** [comment]
Duplicated of already fixed issue #63. A new build with that fix is hopefully coming soon:tm:.
