### ISSUE TITLE
Error during initialization

### ISSUE THREAD

**Issue by Janrupf** [Almighty-Alpaca/JetBrains-Discord-Integration#69]
Multiple IDEs sometimes failt to start due to an exception. (I don't know kotlin, but looks like the kotlin version of a NPE).
I have this issue with WebStorm, Clion and IntelliJ, possibly others.
My operating system is Arch Linux kernel version 5.3.1-arch1-1-ARCH.

The following stacktrace appears:
```
Plugin 'com.almightyalpaca.intellij.plugins.discord' failed to initialize and will be disabled.  Please restart WebStorm.

com.almightyalpaca.jetbrains.plugins.discord.plugin.dependencies.kotlin.TypeCastException: null cannot be cast to non-null type com.intellij.openapi.actionSystem.DefaultActionGroup
    at com.almightyalpaca.jetbrains.plugins.discord.plugin.actions.impl.ActionComponentImpl.initComponent(ActionComponentImpl.kt:39)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:503)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponents(ComponentManagerImpl.java:126)
    at com.intellij.openapi.application.impl.ApplicationImpl.lambda$load$7(ApplicationImpl.java:414)
    at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:169)
    at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:591)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:537)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:156)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:414)
    at com.intellij.idea.IdeaApplication.lambda$executeInitAppInEdt$5(IdeaApplication.java:150)
    at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
    at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
    at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
    at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
    at java.base/java.security.AccessController.doPrivileged(Native Method)
    at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
    at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:384)
    at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
    at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
    at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:117)
    at java.desktop/java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:190)
    at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:235)
    at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:233)
    at java.base/java.security.AccessController.doPrivileged(Native Method)
    at java.desktop/java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:233)
    at java.desktop/java.awt.Dialog.show(Dialog.java:1063)
    at java.desktop/javax.swing.JOptionPane.showOptionDialog(JOptionPane.java:874)
    at java.desktop/javax.swing.JOptionPane.showMessageDialog(JOptionPane.java:670)
    at java.desktop/javax.swing.JOptionPane.showMessageDialog(JOptionPane.java:641)
    at com.intellij.idea.Main.showMessage(Main.java:190)
    at com.intellij.idea.Main.showMessage(Main.java:149)
    at com.intellij.ide.plugins.MainRunner.processException(MainRunner.java:116)
    at com.intellij.ide.IdeEventQueue.processException(IdeEventQueue.java:571)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:387)
    at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
    at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
    at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
    at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
    at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

The exception happens very early during initialization ([Image showing the dialog as a reference](https://imgur.com/a/siaQW3q)).

This does not always happen when starting any IDE, so it might be a race condition?

**Comment by Almighty-Alpaca** [comment]
This indeed is a kind of NPE. More specifically when trying to cast `null` to a non-nullable type (those exist in Kotlin). 

What is weird here is that it happens when the _Tools_ category in the menu bar at the top doesn't exist (yet). Is it present in the IDE after the error happens?

**Comment by Janrupf** [comment]
When the error happens the IDE terminates and has to be restarted manually. From there it often takes 2 launches to get it running again. This could be a bug in the IntelliJ platform, but I'm not sure since I've only seen this issue with the discord plugin.

**Comment by Almighty-Alpaca** [comment]
I've never found what exactly caused this issue but the code involved has just been removed so this shouldn't happen anymore.
