### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by jiangdashao** [Almighty-Alpaca/JetBrains-Discord-Integration#74]
Not working, and I got this error:

```java
java.lang.AssertionError: Already disposed: Project (name=Matrix, containerState=DISPOSE_COMPLETED, componentStore=D:\IDEAProjects\Matrix) 
	at com.intellij.openapi.components.impl.ComponentManagerImpl.lambda$throwAlreadyDisposed$0(ComponentManagerImpl.java:153)
	at com.intellij.openapi.application.ReadAction.lambda$run$1(ReadAction.java:62)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:825)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:69)
	at com.intellij.openapi.application.ReadAction.run(ReadAction.java:62)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.throwAlreadyDisposed(ComponentManagerImpl.java:151)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.getPicoContainer(ComponentManagerImpl.java:144)
	at com.intellij.serviceContainer.PlatformComponentManagerImpl.getService(PlatformComponentManagerImpl.kt:286)
	at com.intellij.openapi.components.ServiceManager.getService(ServiceManager.java:22)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.settings.ProjectSettingsKt.getSettings(ProjectSettings.kt:41)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.renderer.RenderContext.<init>(RenderContext.kt:34)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.gui.preview.PreviewRenderer.draw(PreviewRenderer.kt:89)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.gui.preview.JPreview$update$1.invokeSuspend(JPreview.kt:54)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.dependencies.kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.dependencies.kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.dependencies.kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.dependencies.kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.dependencies.kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:740)
```

**Comment by Almighty-Alpaca** [comment]
Closing this in favor of #63.
