### ISSUE TITLE
Error getting Bintray languages

### ISSUE THREAD

**Issue by Leonardlasardine** [Almighty-Alpaca/JetBrains-Discord-Integration#97]
I was using Edu tools while codding in JetBrains Academy/Java Developer and this error appended and we tell me to report it.

```
Error getting Bintray languages

java.lang.RuntimeException: java.net.SocketTimeoutException: Read timed out
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.source.bintray.BintraySource$get$$inlined$suspendCancellableCoroutine$lambda$1.onFailure(BintraySource.kt:182)
	at com.almightyalpaca.jetbrains.plugins.discord.dependencies.okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:510)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
	Suppressed: java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.net.SocketTimeoutException: Read timed out
		at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
		at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1999)
		at com.almightyalpaca.jetbrains.plugins.discord.plugin.source.bintray.BintraySource$readLanguages$2$map$2.apply(BintraySource.kt:138)
		at com.almightyalpaca.jetbrains.plugins.discord.plugin.source.bintray.BintraySource$readLanguages$2$map$2.apply(BintraySource.kt:41)
		at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
		at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
		at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654)
		at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
		at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
		at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
		at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
		at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
		at com.almightyalpaca.jetbrains.plugins.discord.shared.utils.StreamUtilsKt.toMap(StreamUtils.kt:23)
		at com.almightyalpaca.jetbrains.plugins.discord.plugin.source.bintray.BintraySource$readLanguages$2.invokeSuspend(BintraySource.kt:140)
		at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
		at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
		at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
		at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
		at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
		at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
	[CIRCULAR REFERENCE:java.lang.RuntimeException: java.net.SocketTimeoutException: Read timed out]
Caused by: java.net.SocketTimeoutException: Read timed out
	at java.base/java.net.SocketInputStream.socketRead0(Native Method)
	at java.base/java.net.SocketInputStream.socketRead(SocketInputStream.java:115)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:168)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:140)
	at java.base/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:448)
	at java.base/sun.security.ssl.SSLSocketInputRecord.bytesInCompletePacket(SSLSocketInputRecord.java:68)
	at java.base/sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:1103)
	at java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:823)
	at com.almightyalpaca.jetbrains.plugins.discord.dependencies.okio.InputStreamSource.read(JvmOkio.kt:90)
	at com.almightyalpaca.jetbrains.plugins.discord.dependencies.okio.AsyncTimeout$source$1.read(AsyncTimeout.kt:129)
	at com.almightyalpaca.jetbrains.plugins.discord.dependencies.okio.RealBufferedSource.indexOf(RealBufferedSource.kt:449)
	at com.almightyalpaca.jetbrains.plugins.discord.dependencies.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.kt:333)
	at com.almightyalpaca.jetbrains.plugins.discord.dependencies.okhttp3.internal.http1.Http1ExchangeCodec.readHeaderLine(Http1ExchangeCodec.kt:207)
	at com.almightyalpaca.jetbrains.plugins.discord.dependencies.okhttp3.internal.http1.Http1ExchangeCodec.readResponseHeaders(Http1ExchangeCodec.kt:178)
	at com.almightyalpaca.jetbrains.plugins.discord.dependencies.okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.kt:106)
	at com.almightyalpaca.jetbrains.plugins.discord.dependencies.okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:79)
	at com.almightyalpaca.jetbrains.plugins.discord.dependencies.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
	at com.almightyalpaca.jetbrains.plugins.discord.dependencies.okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34)
	at com.almightyalpaca.jetbrains.plugins.discord.dependencies.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
	at com.almightyalpaca.jetbrains.plugins.discord.dependencies.okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:82)
	at com.almightyalpaca.jetbrains.plugins.discord.dependencies.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
	at com.almightyalpaca.jetbrains.plugins.discord.dependencies.okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
	at com.almightyalpaca.jetbrains.plugins.discord.dependencies.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
	at com.almightyalpaca.jetbrains.plugins.discord.dependencies.okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
	at com.almightyalpaca.jetbrains.plugins.discord.dependencies.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
	at com.almightyalpaca.jetbrains.plugins.discord.dependencies.okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:197)
	at com.almightyalpaca.jetbrains.plugins.discord.dependencies.okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:502)
	... 3 more
```

**Comment by Almighty-Alpaca** [comment]
Duplicated of #95
